// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
	AddVoucherCreditsCreditsVouchersPostData,
	AddVoucherCreditsCreditsVouchersPostErrors,
	AddVoucherCreditsCreditsVouchersPostResponses,
	CancelPaymentsCancelPostData,
	CancelPaymentsCancelPostErrors,
	CancelPaymentsCancelPostResponses,
	ChangeVoucherExpirationCreditsVoucherExpirationPostData,
	ChangeVoucherExpirationCreditsVoucherExpirationPostErrors,
	ChangeVoucherExpirationCreditsVoucherExpirationPostResponses,
	CheckAuthStatusAuthStatusGetData,
	CheckAuthStatusAuthStatusGetErrors,
	CheckAuthStatusAuthStatusGetResponses,
	CliCodeAuthCliCodePostData,
	CliCodeAuthCliCodePostErrors,
	CliCodeAuthCliCodePostResponses,
	CreateApiKeyApiKeysPostData,
	CreateApiKeyApiKeysPostErrors,
	CreateApiKeyApiKeysPostResponses,
	CreateCliApiKeyApiKeysCliPostData,
	CreateCliApiKeyApiKeysCliPostErrors,
	CreateCliApiKeyApiKeysCliPostResponses,
	DeleteApiKeyApiKeysKeyIdDeleteData,
	DeleteApiKeyApiKeysKeyIdDeleteErrors,
	DeleteApiKeyApiKeysKeyIdDeleteResponses,
	DowngradePaymentsDowngradePostData,
	DowngradePaymentsDowngradePostErrors,
	DowngradePaymentsDowngradePostResponses,
	ExchangeCodeAuthExchangePostData,
	ExchangeCodeAuthExchangePostErrors,
	ExchangeCodeAuthExchangePostResponses,
	GetAdminAllApiKeysApiKeysAdminListGetData,
	GetAdminAllApiKeysApiKeysAdminListGetErrors,
	GetAdminAllApiKeysApiKeysAdminListGetResponses,
	GetAggregateUsersStatsStatsGlobalUsersGetData,
	GetAggregateUsersStatsStatsGlobalUsersGetErrors,
	GetAggregateUsersStatsStatsGlobalUsersGetResponses,
	GetApiKeysApiKeysGetData,
	GetApiKeysApiKeysGetErrors,
	GetApiKeysApiKeysGetResponses,
	GetAuthMessageAuthMessagePostData,
	GetAuthMessageAuthMessagePostErrors,
	GetAuthMessageAuthMessagePostResponses,
	GetChatApiKeyApiKeysChatGetData,
	GetChatApiKeyApiKeysChatGetErrors,
	GetChatApiKeyApiKeysChatGetResponses,
	GetChatCallsStatsStatsGlobalChatCallsGetData,
	GetChatCallsStatsStatsGlobalChatCallsGetErrors,
	GetChatCallsStatsStatsGlobalChatCallsGetResponses,
	GetChatTokensStatsStatsGlobalChatTokensGetData,
	GetChatTokensStatsStatsGlobalChatTokensGetErrors,
	GetChatTokensStatsStatsGlobalChatTokensGetResponses,
	GetChatUsersStatsStatsGlobalChatUsersGetData,
	GetChatUsersStatsStatsGlobalChatUsersGetErrors,
	GetChatUsersStatsStatsGlobalChatUsersGetResponses,
	GetCliApiKeysApiKeysCliGetData,
	GetCliApiKeysApiKeysCliGetErrors,
	GetCliApiKeysApiKeysCliGetResponses,
	GetDashboardStatsStatsDashboardGetData,
	GetDashboardStatsStatsDashboardGetErrors,
	GetDashboardStatsStatsDashboardGetResponses,
	GetGlobalSummaryStatsGlobalSummaryGetData,
	GetGlobalSummaryStatsGlobalSummaryGetErrors,
	GetGlobalSummaryStatsGlobalSummaryGetResponses,
	GetInferenceCallsStatsStatsGlobalKeyTypeCallsGetData,
	GetInferenceCallsStatsStatsGlobalKeyTypeCallsGetErrors,
	GetInferenceCallsStatsStatsGlobalKeyTypeCallsGetResponses,
	GetInferenceCreditsStatsStatsGlobalKeyTypeCreditsGetData,
	GetInferenceCreditsStatsStatsGlobalKeyTypeCreditsGetErrors,
	GetInferenceCreditsStatsStatsGlobalKeyTypeCreditsGetResponses,
	GetInferenceTokensStatsStatsGlobalKeyTypeTokensGetData,
	GetInferenceTokensStatsStatsGlobalKeyTypeTokensGetErrors,
	GetInferenceTokensStatsStatsGlobalKeyTypeTokensGetResponses,
	GetInferenceUsersStatsStatsGlobalKeyTypeUsersGetData,
	GetInferenceUsersStatsStatsGlobalKeyTypeUsersGetErrors,
	GetInferenceUsersStatsStatsGlobalKeyTypeUsersGetResponses,
	GetMeAuthMeGetData,
	GetMeAuthMeGetErrors,
	GetMeAuthMeGetResponses,
	GetOrCreateApiKeyLiberclawApiKeyPostData,
	GetOrCreateApiKeyLiberclawApiKeyPostErrors,
	GetOrCreateApiKeyLiberclawApiKeyPostResponses,
	GetSubscriptionPaymentsSubscriptionGetData,
	GetSubscriptionPaymentsSubscriptionGetErrors,
	GetSubscriptionPaymentsSubscriptionGetResponses,
	GetTransactionHistoryCreditsTransactionsGetData,
	GetTransactionHistoryCreditsTransactionsGetErrors,
	GetTransactionHistoryCreditsTransactionsGetResponses,
	GetUsageStatsStatsUsageGetData,
	GetUsageStatsStatsUsageGetErrors,
	GetUsageStatsStatsUsageGetResponses,
	GetUserBalanceCreditsBalanceGetData,
	GetUserBalanceCreditsBalanceGetErrors,
	GetUserBalanceCreditsBalanceGetResponses,
	GetUserLiberclawUserGetData,
	GetUserLiberclawUserGetErrors,
	GetUserLiberclawUserGetResponses,
	GetVouchersCreditsVouchersGetData,
	GetVouchersCreditsVouchersGetErrors,
	GetVouchersCreditsVouchersGetResponses,
	GetX402PricesX402PricesGetData,
	GetX402PricesX402PricesGetErrors,
	GetX402PricesX402PricesGetResponses,
	LinkWalletRouteAuthLinkWalletPostData,
	LinkWalletRouteAuthLinkWalletPostErrors,
	LinkWalletRouteAuthLinkWalletPostResponses,
	ListProvidersPaymentsProvidersGetData,
	ListProvidersPaymentsProvidersGetErrors,
	ListProvidersPaymentsProvidersGetResponses,
	ListTiersPaymentsTiersGetData,
	ListTiersPaymentsTiersGetResponses,
	LoginEmailAuthLoginEmailPostData,
	LoginEmailAuthLoginEmailPostErrors,
	LoginEmailAuthLoginEmailPostResponses,
	LoginWithWalletAuthLoginPostData,
	LoginWithWalletAuthLoginPostErrors,
	LoginWithWalletAuthLoginPostResponses,
	LogoutAuthLogoutPostData,
	LogoutAuthLogoutPostErrors,
	LogoutAuthLogoutPostResponses,
	OauthCallbackAuthOauthProviderCallbackGetData,
	OauthCallbackAuthOauthProviderCallbackGetErrors,
	OauthCallbackAuthOauthProviderCallbackGetResponses,
	OauthStartAuthOauthProviderGetData,
	OauthStartAuthOauthProviderGetErrors,
	OauthStartAuthOauthProviderGetResponses,
	ProcessBaseLtaiTransactionsCreditsLtaiBaseProcessPostData,
	ProcessBaseLtaiTransactionsCreditsLtaiBaseProcessPostResponses,
	ProcessSolanaLtaiTransactionsCreditsLtaiSolanaProcessPostData,
	ProcessSolanaLtaiTransactionsCreditsLtaiSolanaProcessPostResponses,
	ProxyChatRequestChatCompletionsPostData,
	ProxyChatRequestChatCompletionsPostErrors,
	ProxyChatRequestChatCompletionsPostResponses,
	RefreshTokensAuthRefreshPostData,
	RefreshTokensAuthRefreshPostErrors,
	RefreshTokensAuthRefreshPostResponses,
	RegionPaymentsRegionGetData,
	RegionPaymentsRegionGetResponses,
	RegisterInferenceCallApiKeysAdminUsagePostData,
	RegisterInferenceCallApiKeysAdminUsagePostErrors,
	RegisterInferenceCallApiKeysAdminUsagePostResponses,
	ResumePaymentsResumePostData,
	ResumePaymentsResumePostErrors,
	ResumePaymentsResumePostResponses,
	SubscribePaymentsSubscribePostData,
	SubscribePaymentsSubscribePostErrors,
	SubscribePaymentsSubscribePostResponses,
	ThirdwebWebhookCreditsThirdwebWebhookPostData,
	ThirdwebWebhookCreditsThirdwebWebhookPostErrors,
	ThirdwebWebhookCreditsThirdwebWebhookPostResponses,
	TopupPacksPaymentsTopupPacksGetData,
	TopupPacksPaymentsTopupPacksGetResponses,
	TopupPaymentsTopupPostData,
	TopupPaymentsTopupPostErrors,
	TopupPaymentsTopupPostResponses,
	UpdateApiKeyApiKeysKeyIdPutData,
	UpdateApiKeyApiKeysKeyIdPutErrors,
	UpdateApiKeyApiKeysKeyIdPutResponses,
	UpdateExpiredCreditTransactionsCreditsUpdateExpiredPostData,
	UpdateExpiredCreditTransactionsCreditsUpdateExpiredPostResponses,
	UpdateMeAuthMePatchData,
	UpdateMeAuthMePatchErrors,
	UpdateMeAuthMePatchResponses,
	UpdateTierLiberclawTierPutData,
	UpdateTierLiberclawTierPutErrors,
	UpdateTierLiberclawTierPutResponses,
	UpgradePaymentsUpgradePostData,
	UpgradePaymentsUpgradePostErrors,
	UpgradePaymentsUpgradePostResponses,
	VerifyMagicLinkRouteAuthVerifyMagicLinkPostData,
	VerifyMagicLinkRouteAuthVerifyMagicLinkPostErrors,
	VerifyMagicLinkRouteAuthVerifyMagicLinkPostResponses,
	WalletChallengeAuthWalletChallengePostData,
	WalletChallengeAuthWalletChallengePostErrors,
	WalletChallengeAuthWalletChallengePostResponses,
	WalletVerifyAuthWalletVerifyPostData,
	WalletVerifyAuthWalletVerifyPostErrors,
	WalletVerifyAuthWalletVerifyPostResponses,
	WebhookPaymentsWebhookProviderIdPostData,
	WebhookPaymentsWebhookProviderIdPostErrors,
	WebhookPaymentsWebhookProviderIdPostResponses,
} from "./types.gen";

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean,
	TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get Auth Message
 *
 * Get the static message for wallet signature authentication.
 */
export const getAuthMessageAuthMessagePost = <ThrowOnError extends boolean = false>(
	options: Options<GetAuthMessageAuthMessagePostData, ThrowOnError>,
): RequestResult<GetAuthMessageAuthMessagePostResponses, GetAuthMessageAuthMessagePostErrors, ThrowOnError> =>
	(options.client ?? client).post<
		GetAuthMessageAuthMessagePostResponses,
		GetAuthMessageAuthMessagePostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/message",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Login With Wallet
 *
 * Authenticate with a wallet signature.
 */
export const loginWithWalletAuthLoginPost = <ThrowOnError extends boolean = false>(
	options: Options<LoginWithWalletAuthLoginPostData, ThrowOnError>,
): RequestResult<LoginWithWalletAuthLoginPostResponses, LoginWithWalletAuthLoginPostErrors, ThrowOnError> =>
	(options.client ?? client).post<
		LoginWithWalletAuthLoginPostResponses,
		LoginWithWalletAuthLoginPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/login",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Check Auth Status
 *
 * Check if the user is authenticated with a valid token.
 */
export const checkAuthStatusAuthStatusGet = <ThrowOnError extends boolean = false>(
	options?: Options<CheckAuthStatusAuthStatusGetData, ThrowOnError>,
): RequestResult<CheckAuthStatusAuthStatusGetResponses, CheckAuthStatusAuthStatusGetErrors, ThrowOnError> =>
	(options?.client ?? client).get<
		CheckAuthStatusAuthStatusGetResponses,
		CheckAuthStatusAuthStatusGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/status",
		...options,
	});

/**
 * Get Me
 *
 * Return the authenticated user's profile (email/OAuth or wallet).
 */
export const getMeAuthMeGet = <ThrowOnError extends boolean = false>(
	options?: Options<GetMeAuthMeGetData, ThrowOnError>,
): RequestResult<GetMeAuthMeGetResponses, GetMeAuthMeGetErrors, ThrowOnError> =>
	(options?.client ?? client).get<GetMeAuthMeGetResponses, GetMeAuthMeGetErrors, ThrowOnError>({
		responseType: "json",
		url: "/auth/me",
		...options,
	});

/**
 * Update Me
 *
 * Update the authenticated user's editable profile (display name).
 */
export const updateMeAuthMePatch = <ThrowOnError extends boolean = false>(
	options: Options<UpdateMeAuthMePatchData, ThrowOnError>,
): RequestResult<UpdateMeAuthMePatchResponses, UpdateMeAuthMePatchErrors, ThrowOnError> =>
	(options.client ?? client).patch<UpdateMeAuthMePatchResponses, UpdateMeAuthMePatchErrors, ThrowOnError>({
		responseType: "json",
		url: "/auth/me",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Wallet Challenge
 *
 * Issue a nonce message for an EVM wallet to sign.
 */
export const walletChallengeAuthWalletChallengePost = <ThrowOnError extends boolean = false>(
	options: Options<WalletChallengeAuthWalletChallengePostData, ThrowOnError>,
): RequestResult<
	WalletChallengeAuthWalletChallengePostResponses,
	WalletChallengeAuthWalletChallengePostErrors,
	ThrowOnError
> =>
	(options.client ?? client).post<
		WalletChallengeAuthWalletChallengePostResponses,
		WalletChallengeAuthWalletChallengePostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/wallet/challenge",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Wallet Verify
 *
 * Verify a signed challenge and return a token pair (creates/links the wallet user).
 */
export const walletVerifyAuthWalletVerifyPost = <ThrowOnError extends boolean = false>(
	options: Options<WalletVerifyAuthWalletVerifyPostData, ThrowOnError>,
): RequestResult<WalletVerifyAuthWalletVerifyPostResponses, WalletVerifyAuthWalletVerifyPostErrors, ThrowOnError> =>
	(options.client ?? client).post<
		WalletVerifyAuthWalletVerifyPostResponses,
		WalletVerifyAuthWalletVerifyPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/wallet/verify",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Login Email
 *
 * Send a magic-link email (token + 6-digit code).
 *
 * The email is dispatched in the background so SMTP latency/failures never block the
 * login request (the magic link is persisted before we return).
 */
export const loginEmailAuthLoginEmailPost = <ThrowOnError extends boolean = false>(
	options: Options<LoginEmailAuthLoginEmailPostData, ThrowOnError>,
): RequestResult<LoginEmailAuthLoginEmailPostResponses, LoginEmailAuthLoginEmailPostErrors, ThrowOnError> =>
	(options.client ?? client).post<
		LoginEmailAuthLoginEmailPostResponses,
		LoginEmailAuthLoginEmailPostErrors,
		ThrowOnError
	>({
		url: "/auth/login/email",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Verify Magic Link Route
 *
 * Verify a magic link (by token or email+code) and return a token pair.
 */
export const verifyMagicLinkRouteAuthVerifyMagicLinkPost = <ThrowOnError extends boolean = false>(
	options: Options<VerifyMagicLinkRouteAuthVerifyMagicLinkPostData, ThrowOnError>,
): RequestResult<
	VerifyMagicLinkRouteAuthVerifyMagicLinkPostResponses,
	VerifyMagicLinkRouteAuthVerifyMagicLinkPostErrors,
	ThrowOnError
> =>
	(options.client ?? client).post<
		VerifyMagicLinkRouteAuthVerifyMagicLinkPostResponses,
		VerifyMagicLinkRouteAuthVerifyMagicLinkPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/verify-magic-link",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Oauth Start
 *
 * Redirect to the provider's consent screen.
 */
export const oauthStartAuthOauthProviderGet = <ThrowOnError extends boolean = false>(
	options: Options<OauthStartAuthOauthProviderGetData, ThrowOnError>,
): RequestResult<OauthStartAuthOauthProviderGetResponses, OauthStartAuthOauthProviderGetErrors, ThrowOnError> =>
	(options.client ?? client).get<
		OauthStartAuthOauthProviderGetResponses,
		OauthStartAuthOauthProviderGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/oauth/{provider}",
		...options,
	});

/**
 * Oauth Callback
 *
 * Provider redirect target: verify state, mint tokens, hand back a one-time code to the frontend.
 */
export const oauthCallbackAuthOauthProviderCallbackGet = <ThrowOnError extends boolean = false>(
	options: Options<OauthCallbackAuthOauthProviderCallbackGetData, ThrowOnError>,
): RequestResult<
	OauthCallbackAuthOauthProviderCallbackGetResponses,
	OauthCallbackAuthOauthProviderCallbackGetErrors,
	ThrowOnError
> =>
	(options.client ?? client).get<
		OauthCallbackAuthOauthProviderCallbackGetResponses,
		OauthCallbackAuthOauthProviderCallbackGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/oauth/{provider}/callback",
		...options,
	});

/**
 * Exchange Code
 *
 * Exchange a one-time OAuth code for the token pair (single-use).
 */
export const exchangeCodeAuthExchangePost = <ThrowOnError extends boolean = false>(
	options: Options<ExchangeCodeAuthExchangePostData, ThrowOnError>,
): RequestResult<ExchangeCodeAuthExchangePostResponses, ExchangeCodeAuthExchangePostErrors, ThrowOnError> =>
	(options.client ?? client).post<
		ExchangeCodeAuthExchangePostResponses,
		ExchangeCodeAuthExchangePostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/exchange",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Cli Code
 *
 * Mint a one-time, PKCE-bound code for the CLI loopback flow.
 *
 * Called by the console SPA once the user is authenticated (by any method). The code is
 * bound to the supplied PKCE challenge and exchanged by the CLI at /auth/exchange.
 */
export const cliCodeAuthCliCodePost = <ThrowOnError extends boolean = false>(
	options: Options<CliCodeAuthCliCodePostData, ThrowOnError>,
): RequestResult<CliCodeAuthCliCodePostResponses, CliCodeAuthCliCodePostErrors, ThrowOnError> =>
	(options.client ?? client).post<CliCodeAuthCliCodePostResponses, CliCodeAuthCliCodePostErrors, ThrowOnError>({
		responseType: "json",
		url: "/auth/cli/code",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Refresh Tokens
 *
 * Rotate a refresh token (one-time use per token) and return a fresh pair.
 */
export const refreshTokensAuthRefreshPost = <ThrowOnError extends boolean = false>(
	options: Options<RefreshTokensAuthRefreshPostData, ThrowOnError>,
): RequestResult<RefreshTokensAuthRefreshPostResponses, RefreshTokensAuthRefreshPostErrors, ThrowOnError> =>
	(options.client ?? client).post<
		RefreshTokensAuthRefreshPostResponses,
		RefreshTokensAuthRefreshPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/refresh",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Logout
 *
 * Clear the session cookie; optionally revoke the session if a refresh token is given.
 */
export const logoutAuthLogoutPost = <ThrowOnError extends boolean = false>(
	options?: Options<LogoutAuthLogoutPostData, ThrowOnError>,
): RequestResult<LogoutAuthLogoutPostResponses, LogoutAuthLogoutPostErrors, ThrowOnError> =>
	(options?.client ?? client).post<LogoutAuthLogoutPostResponses, LogoutAuthLogoutPostErrors, ThrowOnError>({
		url: "/auth/logout",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});

/**
 * Link Wallet Route
 *
 * Attach a verified EVM wallet to the logged-in user (e.g. a fiat user adding crypto).
 */
export const linkWalletRouteAuthLinkWalletPost = <ThrowOnError extends boolean = false>(
	options: Options<LinkWalletRouteAuthLinkWalletPostData, ThrowOnError>,
): RequestResult<LinkWalletRouteAuthLinkWalletPostResponses, LinkWalletRouteAuthLinkWalletPostErrors, ThrowOnError> =>
	(options.client ?? client).post<
		LinkWalletRouteAuthLinkWalletPostResponses,
		LinkWalletRouteAuthLinkWalletPostErrors,
		ThrowOnError
	>({
		url: "/auth/link/wallet",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Process Base Ltai Transactions
 *
 * Process credit purchase with $LTAI transactions in Base
 */
export const processBaseLtaiTransactionsCreditsLtaiBaseProcessPost = <ThrowOnError extends boolean = false>(
	options?: Options<ProcessBaseLtaiTransactionsCreditsLtaiBaseProcessPostData, ThrowOnError>,
): RequestResult<ProcessBaseLtaiTransactionsCreditsLtaiBaseProcessPostResponses, unknown, ThrowOnError> =>
	(options?.client ?? client).post<
		ProcessBaseLtaiTransactionsCreditsLtaiBaseProcessPostResponses,
		unknown,
		ThrowOnError
	>({
		responseType: "json",
		url: "/credits/ltai/base/process",
		...options,
	});

/**
 * Process Solana Ltai Transactions
 *
 * Process credit purchase with $LTAI in solana blockchain
 */
export const processSolanaLtaiTransactionsCreditsLtaiSolanaProcessPost = <ThrowOnError extends boolean = false>(
	options?: Options<ProcessSolanaLtaiTransactionsCreditsLtaiSolanaProcessPostData, ThrowOnError>,
): RequestResult<ProcessSolanaLtaiTransactionsCreditsLtaiSolanaProcessPostResponses, unknown, ThrowOnError> =>
	(options?.client ?? client).post<
		ProcessSolanaLtaiTransactionsCreditsLtaiSolanaProcessPostResponses,
		unknown,
		ThrowOnError
	>({
		responseType: "json",
		url: "/credits/ltai/solana/process",
		...options,
	});

/**
 * Thirdweb Webhook
 *
 * Receive webhooks from Thirdweb
 */
export const thirdwebWebhookCreditsThirdwebWebhookPost = <ThrowOnError extends boolean = false>(
	options: Options<ThirdwebWebhookCreditsThirdwebWebhookPostData, ThrowOnError>,
): RequestResult<
	ThirdwebWebhookCreditsThirdwebWebhookPostResponses,
	ThirdwebWebhookCreditsThirdwebWebhookPostErrors,
	ThrowOnError
> =>
	(options.client ?? client).post<
		ThirdwebWebhookCreditsThirdwebWebhookPostResponses,
		ThirdwebWebhookCreditsThirdwebWebhookPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/credits/thirdweb/webhook",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Update Expired Credit Transactions
 *
 * Deactivate credits with a past expiration date.
 */
export const updateExpiredCreditTransactionsCreditsUpdateExpiredPost = <ThrowOnError extends boolean = false>(
	options?: Options<UpdateExpiredCreditTransactionsCreditsUpdateExpiredPostData, ThrowOnError>,
): RequestResult<UpdateExpiredCreditTransactionsCreditsUpdateExpiredPostResponses, unknown, ThrowOnError> =>
	(options?.client ?? client).post<
		UpdateExpiredCreditTransactionsCreditsUpdateExpiredPostResponses,
		unknown,
		ThrowOnError
	>({
		responseType: "json",
		url: "/credits/update-expired",
		...options,
	});

/**
 * Get User Balance
 *
 * Get the current credit balance for authenticated user.
 */
export const getUserBalanceCreditsBalanceGet = <ThrowOnError extends boolean = false>(
	options?: Options<GetUserBalanceCreditsBalanceGetData, ThrowOnError>,
): RequestResult<GetUserBalanceCreditsBalanceGetResponses, GetUserBalanceCreditsBalanceGetErrors, ThrowOnError> =>
	(options?.client ?? client).get<
		GetUserBalanceCreditsBalanceGetResponses,
		GetUserBalanceCreditsBalanceGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/credits/balance",
		...options,
	});

/**
 * Get Transaction History
 *
 * Get transaction history for authenticated user
 */
export const getTransactionHistoryCreditsTransactionsGet = <ThrowOnError extends boolean = false>(
	options?: Options<GetTransactionHistoryCreditsTransactionsGetData, ThrowOnError>,
): RequestResult<
	GetTransactionHistoryCreditsTransactionsGetResponses,
	GetTransactionHistoryCreditsTransactionsGetErrors,
	ThrowOnError
> =>
	(options?.client ?? client).get<
		GetTransactionHistoryCreditsTransactionsGetResponses,
		GetTransactionHistoryCreditsTransactionsGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/credits/transactions",
		...options,
	});

/**
 * Get Vouchers
 *
 * Get all vouchers for a specific address
 */
export const getVouchersCreditsVouchersGet = <ThrowOnError extends boolean = false>(
	options: Options<GetVouchersCreditsVouchersGetData, ThrowOnError>,
): RequestResult<GetVouchersCreditsVouchersGetResponses, GetVouchersCreditsVouchersGetErrors, ThrowOnError> =>
	(options.client ?? client).get<
		GetVouchersCreditsVouchersGetResponses,
		GetVouchersCreditsVouchersGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/credits/vouchers",
		...options,
	});

/**
 * Add Voucher Credits
 *
 * Add credits via voucher to a specific address
 */
export const addVoucherCreditsCreditsVouchersPost = <ThrowOnError extends boolean = false>(
	options: Options<AddVoucherCreditsCreditsVouchersPostData, ThrowOnError>,
): RequestResult<
	AddVoucherCreditsCreditsVouchersPostResponses,
	AddVoucherCreditsCreditsVouchersPostErrors,
	ThrowOnError
> =>
	(options.client ?? client).post<
		AddVoucherCreditsCreditsVouchersPostResponses,
		AddVoucherCreditsCreditsVouchersPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/credits/vouchers",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Change Voucher Expiration
 *
 * Change a voucher's expiration date
 */
export const changeVoucherExpirationCreditsVoucherExpirationPost = <ThrowOnError extends boolean = false>(
	options: Options<ChangeVoucherExpirationCreditsVoucherExpirationPostData, ThrowOnError>,
): RequestResult<
	ChangeVoucherExpirationCreditsVoucherExpirationPostResponses,
	ChangeVoucherExpirationCreditsVoucherExpirationPostErrors,
	ThrowOnError
> =>
	(options.client ?? client).post<
		ChangeVoucherExpirationCreditsVoucherExpirationPostResponses,
		ChangeVoucherExpirationCreditsVoucherExpirationPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/credits/voucher/expiration",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Get Api Keys
 */
export const getApiKeysApiKeysGet = <ThrowOnError extends boolean = false>(
	options?: Options<GetApiKeysApiKeysGetData, ThrowOnError>,
): RequestResult<GetApiKeysApiKeysGetResponses, GetApiKeysApiKeysGetErrors, ThrowOnError> =>
	(options?.client ?? client).get<GetApiKeysApiKeysGetResponses, GetApiKeysApiKeysGetErrors, ThrowOnError>({
		responseType: "json",
		url: "/api-keys",
		...options,
	});

/**
 * Create Api Key
 */
export const createApiKeyApiKeysPost = <ThrowOnError extends boolean = false>(
	options: Options<CreateApiKeyApiKeysPostData, ThrowOnError>,
): RequestResult<CreateApiKeyApiKeysPostResponses, CreateApiKeyApiKeysPostErrors, ThrowOnError> =>
	(options.client ?? client).post<CreateApiKeyApiKeysPostResponses, CreateApiKeyApiKeysPostErrors, ThrowOnError>({
		responseType: "json",
		url: "/api-keys",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Get Chat Api Key
 */
export const getChatApiKeyApiKeysChatGet = <ThrowOnError extends boolean = false>(
	options?: Options<GetChatApiKeyApiKeysChatGetData, ThrowOnError>,
): RequestResult<GetChatApiKeyApiKeysChatGetResponses, GetChatApiKeyApiKeysChatGetErrors, ThrowOnError> =>
	(options?.client ?? client).get<
		GetChatApiKeyApiKeysChatGetResponses,
		GetChatApiKeyApiKeysChatGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/api-keys/chat",
		...options,
	});

/**
 * Get Cli Api Keys
 */
export const getCliApiKeysApiKeysCliGet = <ThrowOnError extends boolean = false>(
	options?: Options<GetCliApiKeysApiKeysCliGetData, ThrowOnError>,
): RequestResult<GetCliApiKeysApiKeysCliGetResponses, GetCliApiKeysApiKeysCliGetErrors, ThrowOnError> =>
	(options?.client ?? client).get<GetCliApiKeysApiKeysCliGetResponses, GetCliApiKeysApiKeysCliGetErrors, ThrowOnError>({
		responseType: "json",
		url: "/api-keys/cli",
		...options,
	});

/**
 * Create Cli Api Key
 *
 * Mint (or rotate in place) the CLI API key for the caller's device.
 *
 * Final step of the CLI browser-SSO login: the CLI calls this with the freshly
 * exchanged session token. Returns the full key once (stored by the CLI).
 */
export const createCliApiKeyApiKeysCliPost = <ThrowOnError extends boolean = false>(
	options: Options<CreateCliApiKeyApiKeysCliPostData, ThrowOnError>,
): RequestResult<CreateCliApiKeyApiKeysCliPostResponses, CreateCliApiKeyApiKeysCliPostErrors, ThrowOnError> =>
	(options.client ?? client).post<
		CreateCliApiKeyApiKeysCliPostResponses,
		CreateCliApiKeyApiKeysCliPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/api-keys/cli",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Delete Api Key
 */
export const deleteApiKeyApiKeysKeyIdDelete = <ThrowOnError extends boolean = false>(
	options: Options<DeleteApiKeyApiKeysKeyIdDeleteData, ThrowOnError>,
): RequestResult<DeleteApiKeyApiKeysKeyIdDeleteResponses, DeleteApiKeyApiKeysKeyIdDeleteErrors, ThrowOnError> =>
	(options.client ?? client).delete<
		DeleteApiKeyApiKeysKeyIdDeleteResponses,
		DeleteApiKeyApiKeysKeyIdDeleteErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/api-keys/{key_id}",
		...options,
	});

/**
 * Update Api Key
 */
export const updateApiKeyApiKeysKeyIdPut = <ThrowOnError extends boolean = false>(
	options: Options<UpdateApiKeyApiKeysKeyIdPutData, ThrowOnError>,
): RequestResult<UpdateApiKeyApiKeysKeyIdPutResponses, UpdateApiKeyApiKeysKeyIdPutErrors, ThrowOnError> =>
	(options.client ?? client).put<UpdateApiKeyApiKeysKeyIdPutResponses, UpdateApiKeyApiKeysKeyIdPutErrors, ThrowOnError>(
		{
			responseType: "json",
			url: "/api-keys/{key_id}",
			...options,
			headers: {
				"Content-Type": "application/json",
				...options.headers,
			},
		},
	);

/**
 * Register Inference Call
 */
export const registerInferenceCallApiKeysAdminUsagePost = <ThrowOnError extends boolean = false>(
	options: Options<RegisterInferenceCallApiKeysAdminUsagePostData, ThrowOnError>,
): RequestResult<
	RegisterInferenceCallApiKeysAdminUsagePostResponses,
	RegisterInferenceCallApiKeysAdminUsagePostErrors,
	ThrowOnError
> =>
	(options.client ?? client).post<
		RegisterInferenceCallApiKeysAdminUsagePostResponses,
		RegisterInferenceCallApiKeysAdminUsagePostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/api-keys/admin/usage",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Get Admin All Api Keys
 */
export const getAdminAllApiKeysApiKeysAdminListGet = <ThrowOnError extends boolean = false>(
	options: Options<GetAdminAllApiKeysApiKeysAdminListGetData, ThrowOnError>,
): RequestResult<
	GetAdminAllApiKeysApiKeysAdminListGetResponses,
	GetAdminAllApiKeysApiKeysAdminListGetErrors,
	ThrowOnError
> =>
	(options.client ?? client).get<
		GetAdminAllApiKeysApiKeysAdminListGetResponses,
		GetAdminAllApiKeysApiKeysAdminListGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/api-keys/admin/list",
		...options,
	});

/**
 * Get Dashboard Stats
 */
export const getDashboardStatsStatsDashboardGet = <ThrowOnError extends boolean = false>(
	options?: Options<GetDashboardStatsStatsDashboardGetData, ThrowOnError>,
): RequestResult<GetDashboardStatsStatsDashboardGetResponses, GetDashboardStatsStatsDashboardGetErrors, ThrowOnError> =>
	(options?.client ?? client).get<
		GetDashboardStatsStatsDashboardGetResponses,
		GetDashboardStatsStatsDashboardGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/stats/dashboard",
		...options,
	});

/**
 * Get Usage Stats
 */
export const getUsageStatsStatsUsageGet = <ThrowOnError extends boolean = false>(
	options: Options<GetUsageStatsStatsUsageGetData, ThrowOnError>,
): RequestResult<GetUsageStatsStatsUsageGetResponses, GetUsageStatsStatsUsageGetErrors, ThrowOnError> =>
	(options.client ?? client).get<GetUsageStatsStatsUsageGetResponses, GetUsageStatsStatsUsageGetErrors, ThrowOnError>({
		responseType: "json",
		url: "/stats/usage",
		...options,
	});

/**
 * Get Chat Calls Stats
 */
export const getChatCallsStatsStatsGlobalChatCallsGet = <ThrowOnError extends boolean = false>(
	options: Options<GetChatCallsStatsStatsGlobalChatCallsGetData, ThrowOnError>,
): RequestResult<
	GetChatCallsStatsStatsGlobalChatCallsGetResponses,
	GetChatCallsStatsStatsGlobalChatCallsGetErrors,
	ThrowOnError
> =>
	(options.client ?? client).get<
		GetChatCallsStatsStatsGlobalChatCallsGetResponses,
		GetChatCallsStatsStatsGlobalChatCallsGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/stats/global/chat/calls",
		...options,
	});

/**
 * Get Chat Tokens Stats
 */
export const getChatTokensStatsStatsGlobalChatTokensGet = <ThrowOnError extends boolean = false>(
	options: Options<GetChatTokensStatsStatsGlobalChatTokensGetData, ThrowOnError>,
): RequestResult<
	GetChatTokensStatsStatsGlobalChatTokensGetResponses,
	GetChatTokensStatsStatsGlobalChatTokensGetErrors,
	ThrowOnError
> =>
	(options.client ?? client).get<
		GetChatTokensStatsStatsGlobalChatTokensGetResponses,
		GetChatTokensStatsStatsGlobalChatTokensGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/stats/global/chat/tokens",
		...options,
	});

/**
 * Get Chat Users Stats
 */
export const getChatUsersStatsStatsGlobalChatUsersGet = <ThrowOnError extends boolean = false>(
	options: Options<GetChatUsersStatsStatsGlobalChatUsersGetData, ThrowOnError>,
): RequestResult<
	GetChatUsersStatsStatsGlobalChatUsersGetResponses,
	GetChatUsersStatsStatsGlobalChatUsersGetErrors,
	ThrowOnError
> =>
	(options.client ?? client).get<
		GetChatUsersStatsStatsGlobalChatUsersGetResponses,
		GetChatUsersStatsStatsGlobalChatUsersGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/stats/global/chat/users",
		...options,
	});

/**
 * Get Inference Calls Stats
 */
export const getInferenceCallsStatsStatsGlobalKeyTypeCallsGet = <ThrowOnError extends boolean = false>(
	options: Options<GetInferenceCallsStatsStatsGlobalKeyTypeCallsGetData, ThrowOnError>,
): RequestResult<
	GetInferenceCallsStatsStatsGlobalKeyTypeCallsGetResponses,
	GetInferenceCallsStatsStatsGlobalKeyTypeCallsGetErrors,
	ThrowOnError
> =>
	(options.client ?? client).get<
		GetInferenceCallsStatsStatsGlobalKeyTypeCallsGetResponses,
		GetInferenceCallsStatsStatsGlobalKeyTypeCallsGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/stats/global/{key_type}/calls",
		...options,
	});

/**
 * Get Inference Tokens Stats
 */
export const getInferenceTokensStatsStatsGlobalKeyTypeTokensGet = <ThrowOnError extends boolean = false>(
	options: Options<GetInferenceTokensStatsStatsGlobalKeyTypeTokensGetData, ThrowOnError>,
): RequestResult<
	GetInferenceTokensStatsStatsGlobalKeyTypeTokensGetResponses,
	GetInferenceTokensStatsStatsGlobalKeyTypeTokensGetErrors,
	ThrowOnError
> =>
	(options.client ?? client).get<
		GetInferenceTokensStatsStatsGlobalKeyTypeTokensGetResponses,
		GetInferenceTokensStatsStatsGlobalKeyTypeTokensGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/stats/global/{key_type}/tokens",
		...options,
	});

/**
 * Get Inference Credits Stats
 */
export const getInferenceCreditsStatsStatsGlobalKeyTypeCreditsGet = <ThrowOnError extends boolean = false>(
	options: Options<GetInferenceCreditsStatsStatsGlobalKeyTypeCreditsGetData, ThrowOnError>,
): RequestResult<
	GetInferenceCreditsStatsStatsGlobalKeyTypeCreditsGetResponses,
	GetInferenceCreditsStatsStatsGlobalKeyTypeCreditsGetErrors,
	ThrowOnError
> =>
	(options.client ?? client).get<
		GetInferenceCreditsStatsStatsGlobalKeyTypeCreditsGetResponses,
		GetInferenceCreditsStatsStatsGlobalKeyTypeCreditsGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/stats/global/{key_type}/credits",
		...options,
	});

/**
 * Get Inference Users Stats
 */
export const getInferenceUsersStatsStatsGlobalKeyTypeUsersGet = <ThrowOnError extends boolean = false>(
	options: Options<GetInferenceUsersStatsStatsGlobalKeyTypeUsersGetData, ThrowOnError>,
): RequestResult<
	GetInferenceUsersStatsStatsGlobalKeyTypeUsersGetResponses,
	GetInferenceUsersStatsStatsGlobalKeyTypeUsersGetErrors,
	ThrowOnError
> =>
	(options.client ?? client).get<
		GetInferenceUsersStatsStatsGlobalKeyTypeUsersGetResponses,
		GetInferenceUsersStatsStatsGlobalKeyTypeUsersGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/stats/global/{key_type}/users",
		...options,
	});

/**
 * Get Aggregate Users Stats
 */
export const getAggregateUsersStatsStatsGlobalUsersGet = <ThrowOnError extends boolean = false>(
	options: Options<GetAggregateUsersStatsStatsGlobalUsersGetData, ThrowOnError>,
): RequestResult<
	GetAggregateUsersStatsStatsGlobalUsersGetResponses,
	GetAggregateUsersStatsStatsGlobalUsersGetErrors,
	ThrowOnError
> =>
	(options.client ?? client).get<
		GetAggregateUsersStatsStatsGlobalUsersGetResponses,
		GetAggregateUsersStatsStatsGlobalUsersGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/stats/global/users",
		...options,
	});

/**
 * Get Global Summary
 */
export const getGlobalSummaryStatsGlobalSummaryGet = <ThrowOnError extends boolean = false>(
	options: Options<GetGlobalSummaryStatsGlobalSummaryGetData, ThrowOnError>,
): RequestResult<
	GetGlobalSummaryStatsGlobalSummaryGetResponses,
	GetGlobalSummaryStatsGlobalSummaryGetErrors,
	ThrowOnError
> =>
	(options.client ?? client).get<
		GetGlobalSummaryStatsGlobalSummaryGetResponses,
		GetGlobalSummaryStatsGlobalSummaryGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/stats/global/summary",
		...options,
	});

/**
 * Proxy Chat Request
 *
 * Proxy requests to LibertAI chat completions API.
 *
 * Always replaces the Authorization header with LIBERTAI_CHAT_DEFAULT_API_KEY from environment.
 * Forwards all request parameters, query params, and body to api.libertai.io/v1/chat/completions.
 *
 * Handles both streaming and non-streaming responses.
 */
export const proxyChatRequestChatCompletionsPost = <ThrowOnError extends boolean = false>(
	options: Options<ProxyChatRequestChatCompletionsPostData, ThrowOnError>,
): RequestResult<
	ProxyChatRequestChatCompletionsPostResponses,
	ProxyChatRequestChatCompletionsPostErrors,
	ThrowOnError
> =>
	(options.client ?? client).post<
		ProxyChatRequestChatCompletionsPostResponses,
		ProxyChatRequestChatCompletionsPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/chat/completions",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Get Or Create Api Key
 *
 * Get or create an API key for a Liberclaw user.
 */
export const getOrCreateApiKeyLiberclawApiKeyPost = <ThrowOnError extends boolean = false>(
	options: Options<GetOrCreateApiKeyLiberclawApiKeyPostData, ThrowOnError>,
): RequestResult<
	GetOrCreateApiKeyLiberclawApiKeyPostResponses,
	GetOrCreateApiKeyLiberclawApiKeyPostErrors,
	ThrowOnError
> =>
	(options.client ?? client).post<
		GetOrCreateApiKeyLiberclawApiKeyPostResponses,
		GetOrCreateApiKeyLiberclawApiKeyPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/liberclaw/api-key",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Update Tier
 *
 * Update a Liberclaw user's tier.
 */
export const updateTierLiberclawTierPut = <ThrowOnError extends boolean = false>(
	options: Options<UpdateTierLiberclawTierPutData, ThrowOnError>,
): RequestResult<UpdateTierLiberclawTierPutResponses, UpdateTierLiberclawTierPutErrors, ThrowOnError> =>
	(options.client ?? client).put<UpdateTierLiberclawTierPutResponses, UpdateTierLiberclawTierPutErrors, ThrowOnError>({
		responseType: "json",
		url: "/liberclaw/tier",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Get User
 *
 * Get Liberclaw user info with usage stats.
 */
export const getUserLiberclawUserGet = <ThrowOnError extends boolean = false>(
	options: Options<GetUserLiberclawUserGetData, ThrowOnError>,
): RequestResult<GetUserLiberclawUserGetResponses, GetUserLiberclawUserGetErrors, ThrowOnError> =>
	(options.client ?? client).get<GetUserLiberclawUserGetResponses, GetUserLiberclawUserGetErrors, ThrowOnError>({
		responseType: "json",
		url: "/liberclaw/user",
		...options,
	});

/**
 * Get X402 Prices
 */
export const getX402PricesX402PricesGet = <ThrowOnError extends boolean = false>(
	options: Options<GetX402PricesX402PricesGetData, ThrowOnError>,
): RequestResult<GetX402PricesX402PricesGetResponses, GetX402PricesX402PricesGetErrors, ThrowOnError> =>
	(options.client ?? client).get<GetX402PricesX402PricesGetResponses, GetX402PricesX402PricesGetErrors, ThrowOnError>({
		responseType: "json",
		url: "/x402/prices",
		...options,
	});

/**
 * List Providers
 *
 * Payment providers available to the authenticated user
 */
export const listProvidersPaymentsProvidersGet = <ThrowOnError extends boolean = false>(
	options?: Options<ListProvidersPaymentsProvidersGetData, ThrowOnError>,
): RequestResult<ListProvidersPaymentsProvidersGetResponses, ListProvidersPaymentsProvidersGetErrors, ThrowOnError> =>
	(options?.client ?? client).get<
		ListProvidersPaymentsProvidersGetResponses,
		ListProvidersPaymentsProvidersGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/payments/providers",
		...options,
	});

/**
 * List Tiers
 *
 * Subscription tiers and their pricing/allowances
 */
export const listTiersPaymentsTiersGet = <ThrowOnError extends boolean = false>(
	options?: Options<ListTiersPaymentsTiersGetData, ThrowOnError>,
): RequestResult<ListTiersPaymentsTiersGetResponses, unknown, ThrowOnError> =>
	(options?.client ?? client).get<ListTiersPaymentsTiersGetResponses, unknown, ThrowOnError>({
		responseType: "json",
		url: "/payments/tiers",
		...options,
	});

/**
 * Region
 *
 * Caller's payment region (currency + display VAT rate), resolved from client IP
 */
export const regionPaymentsRegionGet = <ThrowOnError extends boolean = false>(
	options?: Options<RegionPaymentsRegionGetData, ThrowOnError>,
): RequestResult<RegionPaymentsRegionGetResponses, unknown, ThrowOnError> =>
	(options?.client ?? client).get<RegionPaymentsRegionGetResponses, unknown, ThrowOnError>({
		responseType: "json",
		url: "/payments/region",
		...options,
	});

/**
 * Topup Packs
 *
 * Fixed EUR top-up packs (gross EUR charge -> USD credits)
 */
export const topupPacksPaymentsTopupPacksGet = <ThrowOnError extends boolean = false>(
	options?: Options<TopupPacksPaymentsTopupPacksGetData, ThrowOnError>,
): RequestResult<TopupPacksPaymentsTopupPacksGetResponses, unknown, ThrowOnError> =>
	(options?.client ?? client).get<TopupPacksPaymentsTopupPacksGetResponses, unknown, ThrowOnError>({
		responseType: "json",
		url: "/payments/topup-packs",
		...options,
	});

/**
 * Topup
 *
 * Open a checkout to buy prepaid credits
 */
export const topupPaymentsTopupPost = <ThrowOnError extends boolean = false>(
	options: Options<TopupPaymentsTopupPostData, ThrowOnError>,
): RequestResult<TopupPaymentsTopupPostResponses, TopupPaymentsTopupPostErrors, ThrowOnError> =>
	(options.client ?? client).post<TopupPaymentsTopupPostResponses, TopupPaymentsTopupPostErrors, ThrowOnError>({
		responseType: "json",
		url: "/payments/topup",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Subscribe
 *
 * Open a checkout to subscribe to a paid tier
 */
export const subscribePaymentsSubscribePost = <ThrowOnError extends boolean = false>(
	options: Options<SubscribePaymentsSubscribePostData, ThrowOnError>,
): RequestResult<SubscribePaymentsSubscribePostResponses, SubscribePaymentsSubscribePostErrors, ThrowOnError> =>
	(options.client ?? client).post<
		SubscribePaymentsSubscribePostResponses,
		SubscribePaymentsSubscribePostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/payments/subscribe",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Upgrade
 *
 * Upgrade to a higher paid tier
 */
export const upgradePaymentsUpgradePost = <ThrowOnError extends boolean = false>(
	options: Options<UpgradePaymentsUpgradePostData, ThrowOnError>,
): RequestResult<UpgradePaymentsUpgradePostResponses, UpgradePaymentsUpgradePostErrors, ThrowOnError> =>
	(options.client ?? client).post<UpgradePaymentsUpgradePostResponses, UpgradePaymentsUpgradePostErrors, ThrowOnError>({
		responseType: "json",
		url: "/payments/upgrade",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Downgrade
 *
 * Queue a downgrade for the end of the billing period
 */
export const downgradePaymentsDowngradePost = <ThrowOnError extends boolean = false>(
	options: Options<DowngradePaymentsDowngradePostData, ThrowOnError>,
): RequestResult<DowngradePaymentsDowngradePostResponses, DowngradePaymentsDowngradePostErrors, ThrowOnError> =>
	(options.client ?? client).post<
		DowngradePaymentsDowngradePostResponses,
		DowngradePaymentsDowngradePostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/payments/downgrade",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Cancel
 *
 * Cancel the current subscription at period end
 */
export const cancelPaymentsCancelPost = <ThrowOnError extends boolean = false>(
	options?: Options<CancelPaymentsCancelPostData, ThrowOnError>,
): RequestResult<CancelPaymentsCancelPostResponses, CancelPaymentsCancelPostErrors, ThrowOnError> =>
	(options?.client ?? client).post<CancelPaymentsCancelPostResponses, CancelPaymentsCancelPostErrors, ThrowOnError>({
		responseType: "json",
		url: "/payments/cancel",
		...options,
	});

/**
 * Resume
 *
 * Undo a scheduled cancellation or downgrade before it takes effect
 */
export const resumePaymentsResumePost = <ThrowOnError extends boolean = false>(
	options?: Options<ResumePaymentsResumePostData, ThrowOnError>,
): RequestResult<ResumePaymentsResumePostResponses, ResumePaymentsResumePostErrors, ThrowOnError> =>
	(options?.client ?? client).post<ResumePaymentsResumePostResponses, ResumePaymentsResumePostErrors, ThrowOnError>({
		responseType: "json",
		url: "/payments/resume",
		...options,
	});

/**
 * Get Subscription
 *
 * Current subscription state for the authenticated user
 */
export const getSubscriptionPaymentsSubscriptionGet = <ThrowOnError extends boolean = false>(
	options?: Options<GetSubscriptionPaymentsSubscriptionGetData, ThrowOnError>,
): RequestResult<
	GetSubscriptionPaymentsSubscriptionGetResponses,
	GetSubscriptionPaymentsSubscriptionGetErrors,
	ThrowOnError
> =>
	(options?.client ?? client).get<
		GetSubscriptionPaymentsSubscriptionGetResponses,
		GetSubscriptionPaymentsSubscriptionGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/payments/subscription",
		...options,
	});

/**
 * Webhook
 *
 * Provider payment webhook (signature-verified)
 */
export const webhookPaymentsWebhookProviderIdPost = <ThrowOnError extends boolean = false>(
	options: Options<WebhookPaymentsWebhookProviderIdPostData, ThrowOnError>,
): RequestResult<
	WebhookPaymentsWebhookProviderIdPostResponses,
	WebhookPaymentsWebhookProviderIdPostErrors,
	ThrowOnError
> =>
	(options.client ?? client).post<
		WebhookPaymentsWebhookProviderIdPostResponses,
		WebhookPaymentsWebhookProviderIdPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/payments/webhook/{provider_id}",
		...options,
	});
