// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from "./client";
import type {
	GetAuthMessageAuthMessagePostData,
	GetAuthMessageAuthMessagePostResponses,
	GetAuthMessageAuthMessagePostErrors,
	LoginWithWalletAuthLoginPostData,
	LoginWithWalletAuthLoginPostResponses,
	LoginWithWalletAuthLoginPostErrors,
	CheckAuthStatusAuthStatusGetData,
	CheckAuthStatusAuthStatusGetResponses,
	CheckAuthStatusAuthStatusGetErrors,
	GetMeAuthMeGetData,
	GetMeAuthMeGetResponses,
	GetMeAuthMeGetErrors,
	WalletChallengeAuthWalletChallengePostData,
	WalletChallengeAuthWalletChallengePostResponses,
	WalletChallengeAuthWalletChallengePostErrors,
	WalletVerifyAuthWalletVerifyPostData,
	WalletVerifyAuthWalletVerifyPostResponses,
	WalletVerifyAuthWalletVerifyPostErrors,
	LoginEmailAuthLoginEmailPostData,
	LoginEmailAuthLoginEmailPostResponses,
	LoginEmailAuthLoginEmailPostErrors,
	VerifyMagicLinkRouteAuthVerifyMagicLinkPostData,
	VerifyMagicLinkRouteAuthVerifyMagicLinkPostResponses,
	VerifyMagicLinkRouteAuthVerifyMagicLinkPostErrors,
	OauthStartAuthOauthProviderGetData,
	OauthStartAuthOauthProviderGetResponses,
	OauthStartAuthOauthProviderGetErrors,
	OauthCallbackAuthOauthProviderCallbackGetData,
	OauthCallbackAuthOauthProviderCallbackGetResponses,
	OauthCallbackAuthOauthProviderCallbackGetErrors,
	ExchangeCodeAuthExchangePostData,
	ExchangeCodeAuthExchangePostResponses,
	ExchangeCodeAuthExchangePostErrors,
	CliCodeAuthCliCodePostData,
	CliCodeAuthCliCodePostResponses,
	CliCodeAuthCliCodePostErrors,
	RefreshTokensAuthRefreshPostData,
	RefreshTokensAuthRefreshPostResponses,
	RefreshTokensAuthRefreshPostErrors,
	LogoutAuthLogoutPostData,
	LogoutAuthLogoutPostResponses,
	LogoutAuthLogoutPostErrors,
	LinkWalletRouteAuthLinkWalletPostData,
	LinkWalletRouteAuthLinkWalletPostResponses,
	LinkWalletRouteAuthLinkWalletPostErrors,
	ProcessBaseLtaiTransactionsCreditsLtaiBaseProcessPostData,
	ProcessBaseLtaiTransactionsCreditsLtaiBaseProcessPostResponses,
	ProcessSolanaLtaiTransactionsCreditsLtaiSolanaProcessPostData,
	ProcessSolanaLtaiTransactionsCreditsLtaiSolanaProcessPostResponses,
	ThirdwebWebhookCreditsThirdwebWebhookPostData,
	ThirdwebWebhookCreditsThirdwebWebhookPostResponses,
	ThirdwebWebhookCreditsThirdwebWebhookPostErrors,
	UpdateExpiredCreditTransactionsCreditsUpdateExpiredPostData,
	UpdateExpiredCreditTransactionsCreditsUpdateExpiredPostResponses,
	GetUserBalanceCreditsBalanceGetData,
	GetUserBalanceCreditsBalanceGetResponses,
	GetUserBalanceCreditsBalanceGetErrors,
	GetTransactionHistoryCreditsTransactionsGetData,
	GetTransactionHistoryCreditsTransactionsGetResponses,
	GetTransactionHistoryCreditsTransactionsGetErrors,
	GetVouchersCreditsVouchersGetData,
	GetVouchersCreditsVouchersGetResponses,
	GetVouchersCreditsVouchersGetErrors,
	AddVoucherCreditsCreditsVouchersPostData,
	AddVoucherCreditsCreditsVouchersPostResponses,
	AddVoucherCreditsCreditsVouchersPostErrors,
	ChangeVoucherExpirationCreditsVoucherExpirationPostData,
	ChangeVoucherExpirationCreditsVoucherExpirationPostResponses,
	ChangeVoucherExpirationCreditsVoucherExpirationPostErrors,
	GetApiKeysApiKeysGetData,
	GetApiKeysApiKeysGetResponses,
	GetApiKeysApiKeysGetErrors,
	CreateApiKeyApiKeysPostData,
	CreateApiKeyApiKeysPostResponses,
	CreateApiKeyApiKeysPostErrors,
	GetChatApiKeyApiKeysChatGetData,
	GetChatApiKeyApiKeysChatGetResponses,
	GetChatApiKeyApiKeysChatGetErrors,
	GetCliApiKeysApiKeysCliGetData,
	GetCliApiKeysApiKeysCliGetResponses,
	GetCliApiKeysApiKeysCliGetErrors,
	CreateCliApiKeyApiKeysCliPostData,
	CreateCliApiKeyApiKeysCliPostResponses,
	CreateCliApiKeyApiKeysCliPostErrors,
	DeleteApiKeyApiKeysKeyIdDeleteData,
	DeleteApiKeyApiKeysKeyIdDeleteResponses,
	DeleteApiKeyApiKeysKeyIdDeleteErrors,
	UpdateApiKeyApiKeysKeyIdPutData,
	UpdateApiKeyApiKeysKeyIdPutResponses,
	UpdateApiKeyApiKeysKeyIdPutErrors,
	RegisterInferenceCallApiKeysAdminUsagePostData,
	RegisterInferenceCallApiKeysAdminUsagePostResponses,
	RegisterInferenceCallApiKeysAdminUsagePostErrors,
	GetAdminAllApiKeysApiKeysAdminListGetData,
	GetAdminAllApiKeysApiKeysAdminListGetResponses,
	GetAdminAllApiKeysApiKeysAdminListGetErrors,
	GetDashboardStatsStatsDashboardGetData,
	GetDashboardStatsStatsDashboardGetResponses,
	GetDashboardStatsStatsDashboardGetErrors,
	GetUsageStatsStatsUsageGetData,
	GetUsageStatsStatsUsageGetResponses,
	GetUsageStatsStatsUsageGetErrors,
	GetCreditsStatsStatsGlobalApiCreditsGetData,
	GetCreditsStatsStatsGlobalApiCreditsGetResponses,
	GetCreditsStatsStatsGlobalApiCreditsGetErrors,
	GetApiStatsStatsGlobalApiCallsGetData,
	GetApiStatsStatsGlobalApiCallsGetResponses,
	GetApiStatsStatsGlobalApiCallsGetErrors,
	GetTokensStatsStatsGlobalApiTokensGetData,
	GetTokensStatsStatsGlobalApiTokensGetResponses,
	GetTokensStatsStatsGlobalApiTokensGetErrors,
	GetChatCallsStatsStatsGlobalChatCallsGetData,
	GetChatCallsStatsStatsGlobalChatCallsGetResponses,
	GetChatCallsStatsStatsGlobalChatCallsGetErrors,
	GetChatTokensStatsStatsGlobalChatTokensGetData,
	GetChatTokensStatsStatsGlobalChatTokensGetResponses,
	GetChatTokensStatsStatsGlobalChatTokensGetErrors,
	GetLiberclawCallsStatsStatsGlobalLiberclawCallsGetData,
	GetLiberclawCallsStatsStatsGlobalLiberclawCallsGetResponses,
	GetLiberclawCallsStatsStatsGlobalLiberclawCallsGetErrors,
	GetLiberclawTokensStatsStatsGlobalLiberclawTokensGetData,
	GetLiberclawTokensStatsStatsGlobalLiberclawTokensGetResponses,
	GetLiberclawTokensStatsStatsGlobalLiberclawTokensGetErrors,
	GetLiberclawCreditsStatsStatsGlobalLiberclawCreditsGetData,
	GetLiberclawCreditsStatsStatsGlobalLiberclawCreditsGetResponses,
	GetLiberclawCreditsStatsStatsGlobalLiberclawCreditsGetErrors,
	GetX402CallsStatsStatsGlobalX402CallsGetData,
	GetX402CallsStatsStatsGlobalX402CallsGetResponses,
	GetX402CallsStatsStatsGlobalX402CallsGetErrors,
	GetX402TokensStatsStatsGlobalX402TokensGetData,
	GetX402TokensStatsStatsGlobalX402TokensGetResponses,
	GetX402TokensStatsStatsGlobalX402TokensGetErrors,
	GetX402CreditsStatsStatsGlobalX402CreditsGetData,
	GetX402CreditsStatsStatsGlobalX402CreditsGetResponses,
	GetX402CreditsStatsStatsGlobalX402CreditsGetErrors,
	GetGlobalSummaryStatsGlobalSummaryGetData,
	GetGlobalSummaryStatsGlobalSummaryGetResponses,
	GetGlobalSummaryStatsGlobalSummaryGetErrors,
	ProxyChatRequestChatCompletionsPostData,
	ProxyChatRequestChatCompletionsPostResponses,
	ProxyChatRequestChatCompletionsPostErrors,
	GetOrCreateApiKeyLiberclawApiKeyPostData,
	GetOrCreateApiKeyLiberclawApiKeyPostResponses,
	GetOrCreateApiKeyLiberclawApiKeyPostErrors,
	UpdateTierLiberclawTierPutData,
	UpdateTierLiberclawTierPutResponses,
	UpdateTierLiberclawTierPutErrors,
	GetUserLiberclawUserGetData,
	GetUserLiberclawUserGetResponses,
	GetUserLiberclawUserGetErrors,
	GetX402PricesX402PricesGetData,
	GetX402PricesX402PricesGetResponses,
	GetX402PricesX402PricesGetErrors,
	ListProvidersPaymentsProvidersGetData,
	ListProvidersPaymentsProvidersGetResponses,
	ListProvidersPaymentsProvidersGetErrors,
	ListTiersPaymentsTiersGetData,
	ListTiersPaymentsTiersGetResponses,
	TopupPaymentsTopupPostData,
	TopupPaymentsTopupPostResponses,
	TopupPaymentsTopupPostErrors,
	SubscribePaymentsSubscribePostData,
	SubscribePaymentsSubscribePostResponses,
	SubscribePaymentsSubscribePostErrors,
	UpgradePaymentsUpgradePostData,
	UpgradePaymentsUpgradePostResponses,
	UpgradePaymentsUpgradePostErrors,
	DowngradePaymentsDowngradePostData,
	DowngradePaymentsDowngradePostResponses,
	DowngradePaymentsDowngradePostErrors,
	CancelPaymentsCancelPostData,
	CancelPaymentsCancelPostResponses,
	CancelPaymentsCancelPostErrors,
	GetSubscriptionPaymentsSubscriptionGetData,
	GetSubscriptionPaymentsSubscriptionGetResponses,
	GetSubscriptionPaymentsSubscriptionGetErrors,
	WebhookPaymentsWebhookProviderIdPostData,
	WebhookPaymentsWebhookProviderIdPostResponses,
	WebhookPaymentsWebhookProviderIdPostErrors,
} from "./types.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<
	TData,
	ThrowOnError
> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: Record<string, unknown>;
};

/**
 * Get Auth Message
 * Get the static message for wallet signature authentication.
 */
export const getAuthMessageAuthMessagePost = <ThrowOnError extends boolean = false>(
	options: Options<GetAuthMessageAuthMessagePostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		GetAuthMessageAuthMessagePostResponses,
		GetAuthMessageAuthMessagePostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/message",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Login With Wallet
 * Authenticate with a wallet signature.
 */
export const loginWithWalletAuthLoginPost = <ThrowOnError extends boolean = false>(
	options: Options<LoginWithWalletAuthLoginPostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		LoginWithWalletAuthLoginPostResponses,
		LoginWithWalletAuthLoginPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/login",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Check Auth Status
 * Check if the user is authenticated with a valid token.
 */
export const checkAuthStatusAuthStatusGet = <ThrowOnError extends boolean = false>(
	options?: Options<CheckAuthStatusAuthStatusGetData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		CheckAuthStatusAuthStatusGetResponses,
		CheckAuthStatusAuthStatusGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/status",
		...options,
	});
};

/**
 * Get Me
 * Return the authenticated user's profile (email/OAuth or wallet).
 */
export const getMeAuthMeGet = <ThrowOnError extends boolean = false>(
	options?: Options<GetMeAuthMeGetData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<GetMeAuthMeGetResponses, GetMeAuthMeGetErrors, ThrowOnError>({
		responseType: "json",
		url: "/auth/me",
		...options,
	});
};

/**
 * Wallet Challenge
 * Issue a nonce message for an EVM wallet to sign.
 */
export const walletChallengeAuthWalletChallengePost = <ThrowOnError extends boolean = false>(
	options: Options<WalletChallengeAuthWalletChallengePostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		WalletChallengeAuthWalletChallengePostResponses,
		WalletChallengeAuthWalletChallengePostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/wallet/challenge",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Wallet Verify
 * Verify a signed challenge and return a token pair (creates/links the wallet user).
 */
export const walletVerifyAuthWalletVerifyPost = <ThrowOnError extends boolean = false>(
	options: Options<WalletVerifyAuthWalletVerifyPostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		WalletVerifyAuthWalletVerifyPostResponses,
		WalletVerifyAuthWalletVerifyPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/wallet/verify",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Login Email
 * Send a magic-link email (token + 6-digit code).
 *
 * The email is dispatched in the background so SMTP latency/failures never block the
 * login request (the magic link is persisted before we return).
 */
export const loginEmailAuthLoginEmailPost = <ThrowOnError extends boolean = false>(
	options: Options<LoginEmailAuthLoginEmailPostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		LoginEmailAuthLoginEmailPostResponses,
		LoginEmailAuthLoginEmailPostErrors,
		ThrowOnError
	>({
		url: "/auth/login/email",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Verify Magic Link Route
 * Verify a magic link (by token or email+code) and return a token pair.
 */
export const verifyMagicLinkRouteAuthVerifyMagicLinkPost = <ThrowOnError extends boolean = false>(
	options: Options<VerifyMagicLinkRouteAuthVerifyMagicLinkPostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		VerifyMagicLinkRouteAuthVerifyMagicLinkPostResponses,
		VerifyMagicLinkRouteAuthVerifyMagicLinkPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/verify-magic-link",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Oauth Start
 * Redirect to the provider's consent screen.
 */
export const oauthStartAuthOauthProviderGet = <ThrowOnError extends boolean = false>(
	options: Options<OauthStartAuthOauthProviderGetData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		OauthStartAuthOauthProviderGetResponses,
		OauthStartAuthOauthProviderGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/oauth/{provider}",
		...options,
	});
};

/**
 * Oauth Callback
 * Provider redirect target: verify state, mint tokens, hand back a one-time code to the frontend.
 */
export const oauthCallbackAuthOauthProviderCallbackGet = <ThrowOnError extends boolean = false>(
	options: Options<OauthCallbackAuthOauthProviderCallbackGetData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		OauthCallbackAuthOauthProviderCallbackGetResponses,
		OauthCallbackAuthOauthProviderCallbackGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/oauth/{provider}/callback",
		...options,
	});
};

/**
 * Exchange Code
 * Exchange a one-time OAuth code for the token pair (single-use).
 */
export const exchangeCodeAuthExchangePost = <ThrowOnError extends boolean = false>(
	options: Options<ExchangeCodeAuthExchangePostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		ExchangeCodeAuthExchangePostResponses,
		ExchangeCodeAuthExchangePostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/exchange",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Cli Code
 * Mint a one-time, PKCE-bound code for the CLI loopback flow.
 *
 * Called by the console SPA once the user is authenticated (by any method). The code is
 * bound to the supplied PKCE challenge and exchanged by the CLI at /auth/exchange.
 */
export const cliCodeAuthCliCodePost = <ThrowOnError extends boolean = false>(
	options: Options<CliCodeAuthCliCodePostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		CliCodeAuthCliCodePostResponses,
		CliCodeAuthCliCodePostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/cli/code",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Refresh Tokens
 * Rotate a refresh token (one-time use per token) and return a fresh pair.
 */
export const refreshTokensAuthRefreshPost = <ThrowOnError extends boolean = false>(
	options: Options<RefreshTokensAuthRefreshPostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		RefreshTokensAuthRefreshPostResponses,
		RefreshTokensAuthRefreshPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/refresh",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Logout
 * Revoke the session backing a refresh token.
 */
export const logoutAuthLogoutPost = <ThrowOnError extends boolean = false>(
	options: Options<LogoutAuthLogoutPostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		LogoutAuthLogoutPostResponses,
		LogoutAuthLogoutPostErrors,
		ThrowOnError
	>({
		url: "/auth/logout",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Link Wallet Route
 * Attach a verified EVM wallet to the logged-in user (e.g. a fiat user adding crypto).
 */
export const linkWalletRouteAuthLinkWalletPost = <ThrowOnError extends boolean = false>(
	options: Options<LinkWalletRouteAuthLinkWalletPostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		LinkWalletRouteAuthLinkWalletPostResponses,
		LinkWalletRouteAuthLinkWalletPostErrors,
		ThrowOnError
	>({
		url: "/auth/link/wallet",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Process Base Ltai Transactions
 * Process credit purchase with $LTAI transactions in Base
 */
export const processBaseLtaiTransactionsCreditsLtaiBaseProcessPost = <ThrowOnError extends boolean = false>(
	options?: Options<ProcessBaseLtaiTransactionsCreditsLtaiBaseProcessPostData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).post<
		ProcessBaseLtaiTransactionsCreditsLtaiBaseProcessPostResponses,
		unknown,
		ThrowOnError
	>({
		responseType: "json",
		url: "/credits/ltai/base/process",
		...options,
	});
};

/**
 * Process Solana Ltai Transactions
 * Process credit purchase with $LTAI in solana blockchain
 */
export const processSolanaLtaiTransactionsCreditsLtaiSolanaProcessPost = <ThrowOnError extends boolean = false>(
	options?: Options<ProcessSolanaLtaiTransactionsCreditsLtaiSolanaProcessPostData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).post<
		ProcessSolanaLtaiTransactionsCreditsLtaiSolanaProcessPostResponses,
		unknown,
		ThrowOnError
	>({
		responseType: "json",
		url: "/credits/ltai/solana/process",
		...options,
	});
};

/**
 * Thirdweb Webhook
 * Receive webhooks from Thirdweb
 */
export const thirdwebWebhookCreditsThirdwebWebhookPost = <ThrowOnError extends boolean = false>(
	options: Options<ThirdwebWebhookCreditsThirdwebWebhookPostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		ThirdwebWebhookCreditsThirdwebWebhookPostResponses,
		ThirdwebWebhookCreditsThirdwebWebhookPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/credits/thirdweb/webhook",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Update Expired Credit Transactions
 * Deactivate credits with a past expiration date.
 */
export const updateExpiredCreditTransactionsCreditsUpdateExpiredPost = <ThrowOnError extends boolean = false>(
	options?: Options<UpdateExpiredCreditTransactionsCreditsUpdateExpiredPostData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).post<
		UpdateExpiredCreditTransactionsCreditsUpdateExpiredPostResponses,
		unknown,
		ThrowOnError
	>({
		responseType: "json",
		url: "/credits/update-expired",
		...options,
	});
};

/**
 * Get User Balance
 * Get the current credit balance for authenticated user.
 */
export const getUserBalanceCreditsBalanceGet = <ThrowOnError extends boolean = false>(
	options?: Options<GetUserBalanceCreditsBalanceGetData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetUserBalanceCreditsBalanceGetResponses,
		GetUserBalanceCreditsBalanceGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/credits/balance",
		...options,
	});
};

/**
 * Get Transaction History
 * Get transaction history for authenticated user
 */
export const getTransactionHistoryCreditsTransactionsGet = <ThrowOnError extends boolean = false>(
	options?: Options<GetTransactionHistoryCreditsTransactionsGetData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetTransactionHistoryCreditsTransactionsGetResponses,
		GetTransactionHistoryCreditsTransactionsGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/credits/transactions",
		...options,
	});
};

/**
 * Get Vouchers
 * Get all vouchers for a specific address
 */
export const getVouchersCreditsVouchersGet = <ThrowOnError extends boolean = false>(
	options: Options<GetVouchersCreditsVouchersGetData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetVouchersCreditsVouchersGetResponses,
		GetVouchersCreditsVouchersGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/credits/vouchers",
		...options,
	});
};

/**
 * Add Voucher Credits
 * Add credits via voucher to a specific address
 */
export const addVoucherCreditsCreditsVouchersPost = <ThrowOnError extends boolean = false>(
	options: Options<AddVoucherCreditsCreditsVouchersPostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		AddVoucherCreditsCreditsVouchersPostResponses,
		AddVoucherCreditsCreditsVouchersPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/credits/vouchers",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Change Voucher Expiration
 * Change a voucher's expiration date
 */
export const changeVoucherExpirationCreditsVoucherExpirationPost = <ThrowOnError extends boolean = false>(
	options: Options<ChangeVoucherExpirationCreditsVoucherExpirationPostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		ChangeVoucherExpirationCreditsVoucherExpirationPostResponses,
		ChangeVoucherExpirationCreditsVoucherExpirationPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/credits/voucher/expiration",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Get Api Keys
 */
export const getApiKeysApiKeysGet = <ThrowOnError extends boolean = false>(
	options?: Options<GetApiKeysApiKeysGetData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetApiKeysApiKeysGetResponses,
		GetApiKeysApiKeysGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/api-keys",
		...options,
	});
};

/**
 * Create Api Key
 */
export const createApiKeyApiKeysPost = <ThrowOnError extends boolean = false>(
	options: Options<CreateApiKeyApiKeysPostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		CreateApiKeyApiKeysPostResponses,
		CreateApiKeyApiKeysPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/api-keys",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Get Chat Api Key
 */
export const getChatApiKeyApiKeysChatGet = <ThrowOnError extends boolean = false>(
	options?: Options<GetChatApiKeyApiKeysChatGetData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetChatApiKeyApiKeysChatGetResponses,
		GetChatApiKeyApiKeysChatGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/api-keys/chat",
		...options,
	});
};

/**
 * Get Cli Api Keys
 */
export const getCliApiKeysApiKeysCliGet = <ThrowOnError extends boolean = false>(
	options?: Options<GetCliApiKeysApiKeysCliGetData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetCliApiKeysApiKeysCliGetResponses,
		GetCliApiKeysApiKeysCliGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/api-keys/cli",
		...options,
	});
};

/**
 * Create Cli Api Key
 * Mint (or rotate in place) the CLI API key for the caller's device.
 *
 * Final step of the CLI browser-SSO login: the CLI calls this with the freshly
 * exchanged session token. Returns the full key once (stored by the CLI).
 */
export const createCliApiKeyApiKeysCliPost = <ThrowOnError extends boolean = false>(
	options: Options<CreateCliApiKeyApiKeysCliPostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		CreateCliApiKeyApiKeysCliPostResponses,
		CreateCliApiKeyApiKeysCliPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/api-keys/cli",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Delete Api Key
 */
export const deleteApiKeyApiKeysKeyIdDelete = <ThrowOnError extends boolean = false>(
	options: Options<DeleteApiKeyApiKeysKeyIdDeleteData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).delete<
		DeleteApiKeyApiKeysKeyIdDeleteResponses,
		DeleteApiKeyApiKeysKeyIdDeleteErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/api-keys/{key_id}",
		...options,
	});
};

/**
 * Update Api Key
 */
export const updateApiKeyApiKeysKeyIdPut = <ThrowOnError extends boolean = false>(
	options: Options<UpdateApiKeyApiKeysKeyIdPutData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).put<
		UpdateApiKeyApiKeysKeyIdPutResponses,
		UpdateApiKeyApiKeysKeyIdPutErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/api-keys/{key_id}",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Register Inference Call
 */
export const registerInferenceCallApiKeysAdminUsagePost = <ThrowOnError extends boolean = false>(
	options: Options<RegisterInferenceCallApiKeysAdminUsagePostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		RegisterInferenceCallApiKeysAdminUsagePostResponses,
		RegisterInferenceCallApiKeysAdminUsagePostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/api-keys/admin/usage",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Get Admin All Api Keys
 */
export const getAdminAllApiKeysApiKeysAdminListGet = <ThrowOnError extends boolean = false>(
	options: Options<GetAdminAllApiKeysApiKeysAdminListGetData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetAdminAllApiKeysApiKeysAdminListGetResponses,
		GetAdminAllApiKeysApiKeysAdminListGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/api-keys/admin/list",
		...options,
	});
};

/**
 * Get Dashboard Stats
 */
export const getDashboardStatsStatsDashboardGet = <ThrowOnError extends boolean = false>(
	options?: Options<GetDashboardStatsStatsDashboardGetData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetDashboardStatsStatsDashboardGetResponses,
		GetDashboardStatsStatsDashboardGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/stats/dashboard",
		...options,
	});
};

/**
 * Get Usage Stats
 */
export const getUsageStatsStatsUsageGet = <ThrowOnError extends boolean = false>(
	options: Options<GetUsageStatsStatsUsageGetData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetUsageStatsStatsUsageGetResponses,
		GetUsageStatsStatsUsageGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/stats/usage",
		...options,
	});
};

/**
 * Get Credits Stats
 */
export const getCreditsStatsStatsGlobalApiCreditsGet = <ThrowOnError extends boolean = false>(
	options: Options<GetCreditsStatsStatsGlobalApiCreditsGetData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetCreditsStatsStatsGlobalApiCreditsGetResponses,
		GetCreditsStatsStatsGlobalApiCreditsGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/stats/global/api/credits",
		...options,
	});
};

/**
 * Get Api Stats
 */
export const getApiStatsStatsGlobalApiCallsGet = <ThrowOnError extends boolean = false>(
	options: Options<GetApiStatsStatsGlobalApiCallsGetData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetApiStatsStatsGlobalApiCallsGetResponses,
		GetApiStatsStatsGlobalApiCallsGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/stats/global/api/calls",
		...options,
	});
};

/**
 * Get Tokens Stats
 */
export const getTokensStatsStatsGlobalApiTokensGet = <ThrowOnError extends boolean = false>(
	options: Options<GetTokensStatsStatsGlobalApiTokensGetData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetTokensStatsStatsGlobalApiTokensGetResponses,
		GetTokensStatsStatsGlobalApiTokensGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/stats/global/api/tokens",
		...options,
	});
};

/**
 * Get Chat Calls Stats
 */
export const getChatCallsStatsStatsGlobalChatCallsGet = <ThrowOnError extends boolean = false>(
	options: Options<GetChatCallsStatsStatsGlobalChatCallsGetData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetChatCallsStatsStatsGlobalChatCallsGetResponses,
		GetChatCallsStatsStatsGlobalChatCallsGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/stats/global/chat/calls",
		...options,
	});
};

/**
 * Get Chat Tokens Stats
 */
export const getChatTokensStatsStatsGlobalChatTokensGet = <ThrowOnError extends boolean = false>(
	options: Options<GetChatTokensStatsStatsGlobalChatTokensGetData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetChatTokensStatsStatsGlobalChatTokensGetResponses,
		GetChatTokensStatsStatsGlobalChatTokensGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/stats/global/chat/tokens",
		...options,
	});
};

/**
 * Get Liberclaw Calls Stats
 */
export const getLiberclawCallsStatsStatsGlobalLiberclawCallsGet = <ThrowOnError extends boolean = false>(
	options: Options<GetLiberclawCallsStatsStatsGlobalLiberclawCallsGetData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetLiberclawCallsStatsStatsGlobalLiberclawCallsGetResponses,
		GetLiberclawCallsStatsStatsGlobalLiberclawCallsGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/stats/global/liberclaw/calls",
		...options,
	});
};

/**
 * Get Liberclaw Tokens Stats
 */
export const getLiberclawTokensStatsStatsGlobalLiberclawTokensGet = <ThrowOnError extends boolean = false>(
	options: Options<GetLiberclawTokensStatsStatsGlobalLiberclawTokensGetData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetLiberclawTokensStatsStatsGlobalLiberclawTokensGetResponses,
		GetLiberclawTokensStatsStatsGlobalLiberclawTokensGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/stats/global/liberclaw/tokens",
		...options,
	});
};

/**
 * Get Liberclaw Credits Stats
 */
export const getLiberclawCreditsStatsStatsGlobalLiberclawCreditsGet = <ThrowOnError extends boolean = false>(
	options: Options<GetLiberclawCreditsStatsStatsGlobalLiberclawCreditsGetData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetLiberclawCreditsStatsStatsGlobalLiberclawCreditsGetResponses,
		GetLiberclawCreditsStatsStatsGlobalLiberclawCreditsGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/stats/global/liberclaw/credits",
		...options,
	});
};

/**
 * Get X402 Calls Stats
 */
export const getX402CallsStatsStatsGlobalX402CallsGet = <ThrowOnError extends boolean = false>(
	options: Options<GetX402CallsStatsStatsGlobalX402CallsGetData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetX402CallsStatsStatsGlobalX402CallsGetResponses,
		GetX402CallsStatsStatsGlobalX402CallsGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/stats/global/x402/calls",
		...options,
	});
};

/**
 * Get X402 Tokens Stats
 */
export const getX402TokensStatsStatsGlobalX402TokensGet = <ThrowOnError extends boolean = false>(
	options: Options<GetX402TokensStatsStatsGlobalX402TokensGetData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetX402TokensStatsStatsGlobalX402TokensGetResponses,
		GetX402TokensStatsStatsGlobalX402TokensGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/stats/global/x402/tokens",
		...options,
	});
};

/**
 * Get X402 Credits Stats
 */
export const getX402CreditsStatsStatsGlobalX402CreditsGet = <ThrowOnError extends boolean = false>(
	options: Options<GetX402CreditsStatsStatsGlobalX402CreditsGetData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetX402CreditsStatsStatsGlobalX402CreditsGetResponses,
		GetX402CreditsStatsStatsGlobalX402CreditsGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/stats/global/x402/credits",
		...options,
	});
};

/**
 * Get Global Summary
 */
export const getGlobalSummaryStatsGlobalSummaryGet = <ThrowOnError extends boolean = false>(
	options: Options<GetGlobalSummaryStatsGlobalSummaryGetData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetGlobalSummaryStatsGlobalSummaryGetResponses,
		GetGlobalSummaryStatsGlobalSummaryGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/stats/global/summary",
		...options,
	});
};

/**
 * Proxy Chat Request
 * Proxy requests to LibertAI chat completions API.
 *
 * Always replaces the Authorization header with LIBERTAI_CHAT_DEFAULT_API_KEY from environment.
 * Forwards all request parameters, query params, and body to api.libertai.io/v1/chat/completions.
 *
 * Handles both streaming and non-streaming responses.
 */
export const proxyChatRequestChatCompletionsPost = <ThrowOnError extends boolean = false>(
	options: Options<ProxyChatRequestChatCompletionsPostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		ProxyChatRequestChatCompletionsPostResponses,
		ProxyChatRequestChatCompletionsPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/chat/completions",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Get Or Create Api Key
 * Get or create an API key for a Liberclaw user.
 */
export const getOrCreateApiKeyLiberclawApiKeyPost = <ThrowOnError extends boolean = false>(
	options: Options<GetOrCreateApiKeyLiberclawApiKeyPostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		GetOrCreateApiKeyLiberclawApiKeyPostResponses,
		GetOrCreateApiKeyLiberclawApiKeyPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/liberclaw/api-key",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Update Tier
 * Update a Liberclaw user's tier.
 */
export const updateTierLiberclawTierPut = <ThrowOnError extends boolean = false>(
	options: Options<UpdateTierLiberclawTierPutData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).put<
		UpdateTierLiberclawTierPutResponses,
		UpdateTierLiberclawTierPutErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/liberclaw/tier",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Get User
 * Get Liberclaw user info with usage stats.
 */
export const getUserLiberclawUserGet = <ThrowOnError extends boolean = false>(
	options: Options<GetUserLiberclawUserGetData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetUserLiberclawUserGetResponses,
		GetUserLiberclawUserGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/liberclaw/user",
		...options,
	});
};

/**
 * Get X402 Prices
 */
export const getX402PricesX402PricesGet = <ThrowOnError extends boolean = false>(
	options: Options<GetX402PricesX402PricesGetData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetX402PricesX402PricesGetResponses,
		GetX402PricesX402PricesGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/x402/prices",
		...options,
	});
};

/**
 * List Providers
 * Payment providers available to the authenticated user
 */
export const listProvidersPaymentsProvidersGet = <ThrowOnError extends boolean = false>(
	options?: Options<ListProvidersPaymentsProvidersGetData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		ListProvidersPaymentsProvidersGetResponses,
		ListProvidersPaymentsProvidersGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/payments/providers",
		...options,
	});
};

/**
 * List Tiers
 * Subscription tiers and their pricing/allowances
 */
export const listTiersPaymentsTiersGet = <ThrowOnError extends boolean = false>(
	options?: Options<ListTiersPaymentsTiersGetData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<ListTiersPaymentsTiersGetResponses, unknown, ThrowOnError>({
		responseType: "json",
		url: "/payments/tiers",
		...options,
	});
};

/**
 * Topup
 * Open a checkout to buy prepaid credits
 */
export const topupPaymentsTopupPost = <ThrowOnError extends boolean = false>(
	options: Options<TopupPaymentsTopupPostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		TopupPaymentsTopupPostResponses,
		TopupPaymentsTopupPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/payments/topup",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Subscribe
 * Open a checkout to subscribe to a paid tier
 */
export const subscribePaymentsSubscribePost = <ThrowOnError extends boolean = false>(
	options: Options<SubscribePaymentsSubscribePostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		SubscribePaymentsSubscribePostResponses,
		SubscribePaymentsSubscribePostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/payments/subscribe",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Upgrade
 * Upgrade to a higher paid tier
 */
export const upgradePaymentsUpgradePost = <ThrowOnError extends boolean = false>(
	options: Options<UpgradePaymentsUpgradePostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		UpgradePaymentsUpgradePostResponses,
		UpgradePaymentsUpgradePostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/payments/upgrade",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Downgrade
 * Queue a downgrade for the end of the billing period
 */
export const downgradePaymentsDowngradePost = <ThrowOnError extends boolean = false>(
	options: Options<DowngradePaymentsDowngradePostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		DowngradePaymentsDowngradePostResponses,
		DowngradePaymentsDowngradePostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/payments/downgrade",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Cancel
 * Cancel the current subscription at period end
 */
export const cancelPaymentsCancelPost = <ThrowOnError extends boolean = false>(
	options?: Options<CancelPaymentsCancelPostData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).post<
		CancelPaymentsCancelPostResponses,
		CancelPaymentsCancelPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/payments/cancel",
		...options,
	});
};

/**
 * Get Subscription
 * Current subscription state for the authenticated user
 */
export const getSubscriptionPaymentsSubscriptionGet = <ThrowOnError extends boolean = false>(
	options?: Options<GetSubscriptionPaymentsSubscriptionGetData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetSubscriptionPaymentsSubscriptionGetResponses,
		GetSubscriptionPaymentsSubscriptionGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/payments/subscription",
		...options,
	});
};

/**
 * Webhook
 * Provider payment webhook (signature-verified)
 */
export const webhookPaymentsWebhookProviderIdPost = <ThrowOnError extends boolean = false>(
	options: Options<WebhookPaymentsWebhookProviderIdPostData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		WebhookPaymentsWebhookProviderIdPostResponses,
		WebhookPaymentsWebhookProviderIdPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/payments/webhook/{provider_id}",
		...options,
	});
};
