// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseURL: "http://localhost:8000" | (string & {});
};

/**
 * AnonUsageResponse
 *
 * Anonymous (logged-out) per-IP chat usage, for the frontend's free-message meter.
 */
export type AnonUsageResponse = {
	/**
	 * Used
	 */
	used: number;
	/**
	 * Limit
	 */
	limit: number;
	/**
	 * Allowed
	 */
	allowed: boolean;
	/**
	 * Resets At
	 */
	resets_at: string | null;
};

/**
 * ApiKey
 */
export type ApiKey = {
	/**
	 * Id
	 */
	id: string;
	/**
	 * Key
	 */
	key: string;
	/**
	 * Name
	 */
	name: string;
	/**
	 * User Id
	 */
	user_id?: string | null;
	/**
	 * User Address
	 */
	user_address?: string | null;
	/**
	 * Created At
	 */
	created_at: string;
	/**
	 * Is Active
	 */
	is_active: boolean;
	/**
	 * Monthly Limit
	 */
	monthly_limit?: number | null;
	type: ApiKeyType;
	/**
	 * Expires At
	 */
	expires_at?: string | null;
};

/**
 * ApiKeyAdminListResponse
 */
export type ApiKeyAdminListResponse = {
	/**
	 * Keys
	 */
	keys: Array<string>;
};

/**
 * ApiKeyCreate
 */
export type ApiKeyCreate = {
	/**
	 * Name
	 */
	name: string;
	/**
	 * Monthly Limit
	 */
	monthly_limit?: number | null;
};

/**
 * ApiKeyListResponse
 */
export type ApiKeyListResponse = {
	/**
	 * Keys
	 */
	keys: Array<FullApiKey>;
};

/**
 * ApiKeyType
 */
export type ApiKeyType = "api" | "chat" | "liberclaw" | "x402" | "cli" | "pool";

/**
 * ApiKeyUpdate
 */
export type ApiKeyUpdate = {
	/**
	 * Name
	 */
	name?: string | null;
	/**
	 * Is Active
	 */
	is_active?: boolean | null;
	/**
	 * Monthly Limit
	 */
	monthly_limit?: number | null;
};

/**
 * AudioInferenceCallData
 *
 * TTS usage as reported by libertai-models: input_tokens carries the character count
 * of the synthesized text; there is no output side. The required Literal type keeps the
 * union unambiguous, and the zero defaults let audio flow through the text billing
 * branches (calculate_price routes to audio pricing by model).
 */
export type AudioInferenceCallData = {
	/**
	 * Key
	 */
	key: string;
	/**
	 * Model Name
	 */
	model_name: string;
	/**
	 * Input Tokens
	 */
	input_tokens: number;
	/**
	 * Output Tokens
	 */
	output_tokens?: number;
	/**
	 * Cached Tokens
	 */
	cached_tokens?: number;
	/**
	 * Type
	 */
	type: "audio";
	/**
	 * Payment Payload
	 */
	payment_payload?: string | null;
	/**
	 * Payment Requirements
	 */
	payment_requirements?: string | null;
};

/**
 * AuthLoginRequest
 */
export type AuthLoginRequest = {
	chain: LibertaiChain;
	/**
	 * Address
	 */
	address: string;
	/**
	 * Signature
	 */
	signature: string;
};

/**
 * AuthLoginResponse
 */
export type AuthLoginResponse = {
	/**
	 * Access Token
	 */
	access_token: string;
	/**
	 * Token Type
	 */
	token_type?: string;
	/**
	 * Address
	 */
	address: string;
};

/**
 * AuthMessageRequest
 */
export type AuthMessageRequest = {
	chain: LibertaiChain;
	/**
	 * Address
	 */
	address: string;
};

/**
 * AuthMessageResponse
 */
export type AuthMessageResponse = {
	/**
	 * Message
	 */
	message: string;
};

/**
 * AuthStatusResponse
 */
export type AuthStatusResponse = {
	/**
	 * Authenticated
	 */
	authenticated: boolean;
	/**
	 * Address
	 */
	address?: string | null;
};

/**
 * Call
 */
export type Call = {
	/**
	 * Date
	 */
	date: string;
	/**
	 * Nb Input Tokens
	 */
	nb_input_tokens: number;
	/**
	 * Nb Output Tokens
	 */
	nb_output_tokens: number;
	/**
	 * Nb Cached Tokens
	 */
	nb_cached_tokens: number;
	/**
	 * Model Name
	 */
	model_name: string;
};

/**
 * CancelResponse
 */
export type CancelResponse = {
	/**
	 * Message
	 */
	message: string;
	/**
	 * Effective Date
	 */
	effective_date?: string | null;
};

/**
 * ChatApiKeyResponse
 */
export type ChatApiKeyResponse = {
	/**
	 * Key
	 */
	key: string;
};

/**
 * ChatCallUsage
 */
export type ChatCallUsage = {
	/**
	 * Model Name
	 */
	model_name: string;
	/**
	 * Used At
	 */
	used_at: string;
	/**
	 * Call Count
	 */
	call_count: number;
};

/**
 * ChatRequest
 */
export type ChatRequest = {
	/**
	 * Model
	 */
	model: string;
	[key: string]: unknown;
};

/**
 * ChatTokenUsage
 */
export type ChatTokenUsage = {
	/**
	 * Date
	 */
	date: string;
	/**
	 * Nb Input Tokens
	 */
	nb_input_tokens: number;
	/**
	 * Nb Output Tokens
	 */
	nb_output_tokens: number;
	/**
	 * Nb Cached Tokens
	 */
	nb_cached_tokens: number;
	/**
	 * Model Name
	 */
	model_name: string;
};

/**
 * CheckoutResponse
 */
export type CheckoutResponse = {
	/**
	 * Checkout Url
	 */
	checkout_url?: string | null;
};

/**
 * ChurnWeek
 */
export type ChurnWeek = {
	/**
	 * Week Start
	 */
	week_start: string;
	/**
	 * New
	 */
	new: number;
	/**
	 * Churned
	 */
	churned: number;
	/**
	 * Net
	 */
	net: number;
};

/**
 * CliApiKeyCreate
 */
export type CliApiKeyCreate = {
	/**
	 * Host
	 */
	host?: string | null;
};

/**
 * CliCodeRequest
 */
export type CliCodeRequest = {
	/**
	 * Challenge
	 */
	challenge: string;
};

/**
 * CliCodeResponse
 */
export type CliCodeResponse = {
	/**
	 * Code
	 */
	code: string;
};

/**
 * CreditBalanceResponse
 */
export type CreditBalanceResponse = {
	/**
	 * Address
	 */
	address: string | null;
	/**
	 * Balance
	 */
	balance: number;
};

/**
 * CreditTransactionProvider
 */
export type CreditTransactionProvider = "ltai_base" | "ltai_solana" | "thirdweb" | "voucher" | "sol_solana" | "revolut";

/**
 * CreditTransactionResponse
 */
export type CreditTransactionResponse = {
	/**
	 * Id
	 */
	id: string;
	/**
	 * External Reference
	 */
	external_reference: string | null;
	/**
	 * Amount
	 */
	amount: number;
	/**
	 * Amount Left
	 */
	amount_left: number;
	provider: CreditTransactionProvider;
	/**
	 * Created At
	 */
	created_at: string;
	/**
	 * Expired At
	 */
	expired_at: string | null;
	/**
	 * Is Active
	 */
	is_active: boolean;
	status: CreditTransactionStatus;
};

/**
 * CreditTransactionStatus
 */
export type CreditTransactionStatus = "pending" | "completed" | "error";

/**
 * CreditTransactionsResponse
 */
export type CreditTransactionsResponse = {
	/**
	 * Address
	 */
	address: string | null;
	/**
	 * Transactions
	 */
	transactions: Array<CreditTransactionResponse>;
};

/**
 * CreditsConsumptionDay
 *
 * Credits consumed on a single day, split by what covered them.
 */
export type CreditsConsumptionDay = {
	/**
	 * Date
	 */
	date: string;
	/**
	 * Tier Credits
	 */
	tier_credits: number;
	/**
	 * Prepaid Credits
	 */
	prepaid_credits: number;
};

/**
 * CreditsUsage
 */
export type CreditsUsage = {
	/**
	 * Credits Used
	 */
	credits_used: number;
	/**
	 * Used At
	 */
	used_at: string;
	/**
	 * Model Name
	 */
	model_name: string;
};

/**
 * CurrentUserResponse
 */
export type CurrentUserResponse = {
	/**
	 * Id
	 */
	id: string;
	/**
	 * Email
	 */
	email?: string | null;
	/**
	 * Display Name
	 */
	display_name?: string | null;
	/**
	 * Avatar Url
	 */
	avatar_url?: string | null;
	/**
	 * Address
	 */
	address?: string | null;
	/**
	 * Is Libertai Staff
	 */
	is_libertai_staff?: boolean;
	/**
	 * Monthly Extra Credit Cap
	 */
	monthly_extra_credit_cap?: number | null;
};

/**
 * DailyActiveUsers
 *
 * Number of distinct users active on a single day.
 */
export type DailyActiveUsers = {
	/**
	 * Date
	 */
	date: string;
	/**
	 * Active Users
	 */
	active_users: number;
};

/**
 * DailyTokens
 *
 * Input and output tokens for a single day.
 */
export type DailyTokens = {
	/**
	 * Input Tokens
	 */
	input_tokens: number;
	/**
	 * Output Tokens
	 */
	output_tokens: number;
};

/**
 * DashboardStats
 *
 * Dashboard statistics for a user.
 */
export type DashboardStats = {
	/**
	 * Address
	 */
	address: string;
	/**
	 * Monthly Usage
	 */
	monthly_usage: {
		[key: string]: number;
	};
	current_month: TokenStats;
};

/**
 * DowngradeRequest
 */
export type DowngradeRequest = {
	/**
	 * Tier
	 */
	tier: string;
};

/**
 * DowngradeResponse
 */
export type DowngradeResponse = {
	/**
	 * New Tier
	 */
	new_tier: string;
	/**
	 * Effective Date
	 */
	effective_date?: string | null;
};

/**
 * EmailLoginRequest
 */
export type EmailLoginRequest = {
	/**
	 * Email
	 */
	email: string;
	/**
	 * Redirect Base
	 */
	redirect_base?: string | null;
};

/**
 * ExchangeRequest
 */
export type ExchangeRequest = {
	/**
	 * Code
	 */
	code: string;
	/**
	 * Verifier
	 */
	verifier?: string | null;
};

/**
 * ExpiredCreditTransaction
 */
export type ExpiredCreditTransaction = {
	/**
	 * Id
	 */
	id: string;
	/**
	 * External Reference
	 */
	external_reference: string | null;
	/**
	 * Address
	 */
	address: string | null;
	/**
	 * Expired At
	 */
	expired_at: string | null;
};

/**
 * ExpiredCreditTransactionsResponse
 */
export type ExpiredCreditTransactionsResponse = {
	/**
	 * Updated Count
	 */
	updated_count: number;
	/**
	 * Transactions
	 */
	transactions: Array<ExpiredCreditTransaction>;
};

/**
 * FullApiKey
 */
export type FullApiKey = {
	/**
	 * Id
	 */
	id: string;
	/**
	 * Key
	 */
	key: string;
	/**
	 * Name
	 */
	name: string;
	/**
	 * User Id
	 */
	user_id?: string | null;
	/**
	 * User Address
	 */
	user_address?: string | null;
	/**
	 * Created At
	 */
	created_at: string;
	/**
	 * Is Active
	 */
	is_active: boolean;
	/**
	 * Monthly Limit
	 */
	monthly_limit?: number | null;
	type: ApiKeyType;
	/**
	 * Expires At
	 */
	expires_at?: string | null;
	/**
	 * Full Key
	 */
	full_key: string;
};

/**
 * GlobalApiStats
 *
 * Api usage statistics for a date range.
 */
export type GlobalApiStats = {
	/**
	 * Total Calls
	 */
	total_calls: number;
	/**
	 * Api Usage
	 */
	api_usage: Array<ModelApiUsage>;
};

/**
 * GlobalChatCallsStats
 *
 * Chat API calls statistics for a date range.
 */
export type GlobalChatCallsStats = {
	/**
	 * Total Calls
	 */
	total_calls: number;
	/**
	 * Chat Usage
	 */
	chat_usage: Array<ChatCallUsage>;
};

/**
 * GlobalChatTokensStats
 *
 * Chat token usage statistics for a date range.
 */
export type GlobalChatTokensStats = {
	/**
	 * Total Input Tokens
	 */
	total_input_tokens: number;
	/**
	 * Total Output Tokens
	 */
	total_output_tokens: number;
	/**
	 * Total Cached Tokens
	 */
	total_cached_tokens: number;
	/**
	 * Token Usage
	 */
	token_usage: Array<ChatTokenUsage>;
};

/**
 * GlobalCreditsConsumptionStats
 *
 * Credit consumption over a date range (api/cli/chat keys), tier-covered vs prepaid.
 */
export type GlobalCreditsConsumptionStats = {
	/**
	 * Total Credits
	 */
	total_credits: number;
	/**
	 * Total Tier Credits
	 */
	total_tier_credits: number;
	/**
	 * Total Prepaid Credits
	 */
	total_prepaid_credits: number;
	/**
	 * Daily
	 */
	daily: Array<CreditsConsumptionDay>;
};

/**
 * GlobalCreditsStats
 *
 * Credit usage statistics for a date range.
 */
export type GlobalCreditsStats = {
	/**
	 * Total Credits Used
	 */
	total_credits_used: number;
	/**
	 * Credits Usage
	 */
	credits_usage: Array<CreditsUsage>;
};

/**
 * GlobalLatestSubscribersStats
 *
 * Most recent plan subscriptions across all providers, newest first.
 *
 * ``total`` is the count of ALL rows matching the status filter (ignoring ``limit``),
 * so callers can show "showing N of total".
 */
export type GlobalLatestSubscribersStats = {
	/**
	 * Subscribers
	 */
	subscribers: Array<LatestSubscriber>;
	/**
	 * Total
	 */
	total: number;
};

/**
 * GlobalSegmentCallsStats
 *
 * Inference calls per subscription segment over a date range (api/cli key types).
 *
 * Segment is the caller's CURRENT active paid tier (go/plus/max) or "free" — no anonymous
 * bucket, since api/cli use per-user keys. Historical tier at call time isn't recorded, so a
 * user's past calls are attributed to their tier today, mirroring the messages-by-segment caveat.
 */
export type GlobalSegmentCallsStats = {
	/**
	 * Total Calls
	 */
	total_calls: number;
	/**
	 * Calls
	 */
	calls: Array<SegmentCallUsage>;
};

/**
 * GlobalSegmentMessagesStats
 *
 * Chat messages per subscription segment over a date range.
 *
 * Sourced from ``chat_requests`` (the full chat history, predating metering), so legacy and
 * current messages share one continuous series. Segment is the sender's CURRENT tier — anon
 * (shared key), free (no paid sub), or the paid tier (go/plus/max). Historical tier at send
 * time isn't recorded, so a user's past messages are attributed to their tier today.
 */
export type GlobalSegmentMessagesStats = {
	/**
	 * Total Messages
	 */
	total_messages: number;
	/**
	 * Messages
	 */
	messages: Array<SegmentMessageUsage>;
};

/**
 * GlobalSubscribersOverTimeStats
 *
 * Active paid subscribers per tier for each day in a date range.
 *
 * A subscription counts toward a day if it had started (``created_at``) on or before that day and
 * had not yet ended — active/overdue subs run to today, cancelled/expired ones end on their last
 * update. Tier is the subscription's CURRENT tier (historical tier changes aren't recorded),
 * mirroring the messages-by-segment caveat.
 */
export type GlobalSubscribersOverTimeStats = {
	/**
	 * Daily
	 */
	daily: Array<TierSubscribersDay>;
};

/**
 * GlobalSubscriptionActivityStats
 *
 * Recent subscription lifecycle events across all providers, newest first.
 */
export type GlobalSubscriptionActivityStats = {
	/**
	 * Events
	 */
	events: Array<SubscriptionActivityEvent>;
};

/**
 * GlobalSubscriptionsChurnStats
 *
 * Revolut, non-trial. new = first activations (upgrade replacements excluded);
 * churned = real terminations (cancelled/expired/finished; upgrades excluded).
 */
export type GlobalSubscriptionsChurnStats = {
	/**
	 * Weekly
	 */
	weekly: Array<ChurnWeek>;
	/**
	 * Total New
	 */
	total_new: number;
	/**
	 * Total Churned
	 */
	total_churned: number;
};

/**
 * GlobalSubscriptionsRevenueStats
 *
 * Revolut (fiat) MRR, nominal and currency-blind; trials excluded. Event-replayed history.
 */
export type GlobalSubscriptionsRevenueStats = {
	/**
	 * Current Mrr
	 */
	current_mrr: number;
	/**
	 * Mrr By Tier
	 */
	mrr_by_tier: Array<MrrByTier>;
	/**
	 * Daily
	 */
	daily: Array<MrrDay>;
};

/**
 * GlobalSubscriptionsStats
 *
 * Current snapshot of the user base by segment.
 *
 * Subscriptions cover all usage (chat/API/CLI), so this is a user-segmentation view, not a
 * chat metric: paid subscribers per tier, registered free users (no active paid sub), and
 * anonymous users (distinct IPs that have used logged-out chat).
 */
export type GlobalSubscriptionsStats = {
	/**
	 * Subscribers By Tier
	 */
	subscribers_by_tier: Array<TierSubscribers>;
	/**
	 * Total Paid Subscribers
	 */
	total_paid_subscribers: number;
	/**
	 * Free Users
	 */
	free_users: number;
	/**
	 * Anonymous Users
	 */
	anonymous_users: number;
};

/**
 * GlobalSummaryStats
 *
 * Global summary statistics across all key types.
 */
export type GlobalSummaryStats = {
	/**
	 * Total Requests
	 */
	total_requests: number;
	/**
	 * Total Input Tokens
	 */
	total_input_tokens: number;
	/**
	 * Total Output Tokens
	 */
	total_output_tokens: number;
};

/**
 * GlobalTokensStats
 */
export type GlobalTokensStats = {
	/**
	 * Total Input Tokens
	 */
	total_input_tokens: number;
	/**
	 * Total Output Tokens
	 */
	total_output_tokens: number;
	/**
	 * Total Cached Tokens
	 */
	total_cached_tokens: number;
	/**
	 * Calls
	 */
	calls: Array<Call>;
};

/**
 * GlobalUsersStats
 *
 * Distinct-user (DAU) statistics for a date range.
 *
 * ``total_unique_users`` counts distinct users over the whole range (NOT the sum of
 * the daily counts, since a user active on several days is counted once).
 */
export type GlobalUsersStats = {
	/**
	 * Total Unique Users
	 */
	total_unique_users: number;
	/**
	 * Daily Active Users
	 */
	daily_active_users: Array<DailyActiveUsers>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
	/**
	 * Detail
	 */
	detail?: Array<ValidationError>;
};

/**
 * ImageInferenceCallData
 */
export type ImageInferenceCallData = {
	/**
	 * Key
	 */
	key: string;
	/**
	 * Model Name
	 */
	model_name: string;
	/**
	 * Image Count
	 */
	image_count: number;
	type?: InferenceCallType;
	/**
	 * Payment Payload
	 */
	payment_payload?: string | null;
	/**
	 * Payment Requirements
	 */
	payment_requirements?: string | null;
};

/**
 * InferenceCallType
 */
export type InferenceCallType = "text" | "image" | "audio";

/**
 * InferenceKeyType
 *
 * Key types whose usage is recorded in ``inference_calls`` (everything but chat).
 *
 * Used as a stats route path param so global inference stats are served by a single
 * set of routes; invalid / chat values are rejected with HTTP 422 automatically.
 */
export type InferenceKeyType = "api" | "liberclaw" | "x402" | "cli";

/**
 * LatestSubscriber
 *
 * A single recent plan subscription with a human-friendly label for its user.
 *
 * ``user_label`` is ``display_name (contact)`` when the user set a name, else the bare
 * ``contact`` (contact resolves email > wallet address > user id).
 */
export type LatestSubscriber = {
	/**
	 * User Label
	 */
	user_label: string;
	/**
	 * Tier
	 */
	tier: string;
	/**
	 * Status
	 */
	status: string;
	/**
	 * Provider
	 */
	provider: string;
	/**
	 * Is Trial
	 */
	is_trial: boolean;
	/**
	 * Cancel At Period End
	 */
	cancel_at_period_end: boolean;
	/**
	 * Created At
	 */
	created_at: string;
	/**
	 * Current Period End
	 */
	current_period_end: string | null;
};

/**
 * LiberclawApiKeyRequest
 */
export type LiberclawApiKeyRequest = {
	/**
	 * User Id
	 */
	user_id: string;
	/**
	 * User Type
	 */
	user_type: string;
};

/**
 * LiberclawApiKeyResponse
 */
export type LiberclawApiKeyResponse = {
	/**
	 * Key
	 */
	key: string;
	/**
	 * Is New
	 */
	is_new: boolean;
};

/**
 * LiberclawTierUpdate
 */
export type LiberclawTierUpdate = {
	/**
	 * User Id
	 */
	user_id: string;
	/**
	 * User Type
	 */
	user_type: string;
	/**
	 * Tier
	 */
	tier: string;
};

/**
 * LiberclawUserResponse
 */
export type LiberclawUserResponse = {
	/**
	 * Id
	 */
	id: string;
	/**
	 * User Id
	 */
	user_id: string;
	/**
	 * User Type
	 */
	user_type: string;
	/**
	 * Tier
	 */
	tier: string;
	/**
	 * Credits Used
	 */
	credits_used: number;
	/**
	 * Credits Limit
	 */
	credits_limit: number;
	/**
	 * Rolling Window Days
	 */
	rolling_window_days: number;
	/**
	 * Created At
	 */
	created_at: string;
};

/**
 * LibertaiChain
 */
export type LibertaiChain = "base" | "solana";

/**
 * LogoutRequest
 */
export type LogoutRequest = {
	/**
	 * Refresh Token
	 */
	refresh_token?: string | null;
};

/**
 * ModelApiUsage
 */
export type ModelApiUsage = {
	/**
	 * Model Name
	 */
	model_name: string;
	/**
	 * Used At
	 */
	used_at: string;
	/**
	 * Call Count
	 */
	call_count: number;
};

/**
 * MrrByTier
 */
export type MrrByTier = {
	/**
	 * Tier
	 */
	tier: string;
	/**
	 * Mrr
	 */
	mrr: number;
};

/**
 * MrrDay
 */
export type MrrDay = {
	/**
	 * Date
	 */
	date: string;
	/**
	 * Mrr
	 */
	mrr: number;
};

/**
 * PaymentProviderResponse
 */
export type PaymentProviderResponse = {
	/**
	 * Id
	 */
	id: string;
	/**
	 * Kind
	 */
	kind: string;
	/**
	 * Label
	 */
	label: string;
	/**
	 * Capabilities
	 */
	capabilities: Array<string>;
	/**
	 * Currencies
	 */
	currencies: Array<string>;
	/**
	 * Chain
	 */
	chain?: string | null;
	/**
	 * Contract Address
	 */
	contract_address?: string | null;
};

/**
 * RefreshRequest
 */
export type RefreshRequest = {
	/**
	 * Refresh Token
	 */
	refresh_token: string;
};

/**
 * RegionResponse
 */
export type RegionResponse = {
	/**
	 * Currency
	 */
	currency: string;
	/**
	 * Vat Rate
	 */
	vat_rate: number;
};

/**
 * ResumeResponse
 */
export type ResumeResponse = {
	/**
	 * Message
	 */
	message: string;
	/**
	 * Tier
	 */
	tier: string;
};

/**
 * SegmentCallUsage
 *
 * Inference calls on a single day for one subscription segment.
 */
export type SegmentCallUsage = {
	/**
	 * Date
	 */
	date: string;
	/**
	 * Segment
	 */
	segment: string;
	/**
	 * Call Count
	 */
	call_count: number;
};

/**
 * SegmentMessageUsage
 *
 * Chat messages on a single day for one subscription segment.
 */
export type SegmentMessageUsage = {
	/**
	 * Date
	 */
	date: string;
	/**
	 * Segment
	 */
	segment: string;
	/**
	 * Message Count
	 */
	message_count: number;
};

/**
 * SubscribeRequest
 */
export type SubscribeRequest = {
	/**
	 * Provider
	 */
	provider?: string;
	/**
	 * Tier
	 */
	tier: string;
	/**
	 * Redirect Base
	 */
	redirect_base?: string | null;
};

/**
 * SubscriptionActivityEvent
 *
 * One lifecycle event, mapped from the raw event log to a human-facing type.
 *
 * ``tier`` is the resulting tier; for upgrades/downgrades ``from_tier`` is the prior tier
 * (render as "from_tier -> tier").
 */
export type SubscriptionActivityEvent = {
	/**
	 * Created At
	 */
	created_at: string;
	type: SubscriptionActivityType;
	/**
	 * User Label
	 */
	user_label: string;
	/**
	 * Tier
	 */
	tier: string;
	/**
	 * From Tier
	 */
	from_tier?: string | null;
	/**
	 * Provider
	 */
	provider: string;
};

/**
 * SubscriptionActivityType
 *
 * Human-facing subscription lifecycle events for the activity feed.
 */
export type SubscriptionActivityType =
	| "subscribed"
	| "upgraded"
	| "downgraded"
	| "cancelled"
	| "churned"
	| "payment_failed";

/**
 * SubscriptionResponse
 *
 * Current subscription state. ``tier`` is the effective entitlement tier.
 */
export type SubscriptionResponse = {
	/**
	 * Tier
	 */
	tier: string;
	/**
	 * Has Subscription
	 */
	has_subscription: boolean;
	/**
	 * Status
	 */
	status?: string | null;
	/**
	 * Provider
	 */
	provider?: string | null;
	/**
	 * Current Period End
	 */
	current_period_end?: string | null;
	/**
	 * Cancel At Period End
	 */
	cancel_at_period_end?: boolean;
	/**
	 * Pending Tier
	 */
	pending_tier?: string | null;
	/**
	 * Is Trial
	 */
	is_trial?: boolean;
	/**
	 * Allowed
	 */
	allowed?: boolean;
	/**
	 * Source
	 */
	source?: string;
	/**
	 * Window 5H Used
	 */
	window_5h_used?: number;
	/**
	 * Window 5H Limit
	 */
	window_5h_limit?: number;
	/**
	 * Window 5H Resets At
	 */
	window_5h_resets_at?: string | null;
	/**
	 * Weekly Used
	 */
	weekly_used?: number;
	/**
	 * Weekly Limit
	 */
	weekly_limit?: number;
	/**
	 * Weekly Resets At
	 */
	weekly_resets_at?: string | null;
	/**
	 * Prepaid Balance
	 */
	prepaid_balance?: number;
	/**
	 * Monthly Extra Credit Cap
	 */
	monthly_extra_credit_cap?: number | null;
	/**
	 * Extra Credits Used This Month
	 */
	extra_credits_used_this_month?: number;
};

/**
 * TextInferenceCallData
 */
export type TextInferenceCallData = {
	/**
	 * Key
	 */
	key: string;
	/**
	 * Model Name
	 */
	model_name: string;
	/**
	 * Input Tokens
	 */
	input_tokens: number;
	/**
	 * Output Tokens
	 */
	output_tokens: number;
	/**
	 * Cached Tokens
	 */
	cached_tokens?: number;
	type?: InferenceCallType | null;
	/**
	 * Payment Payload
	 */
	payment_payload?: string | null;
	/**
	 * Payment Requirements
	 */
	payment_requirements?: string | null;
};

/**
 * ThirdwebOnchainTransactionData
 */
export type ThirdwebOnchainTransactionData = {
	/**
	 * Transactionid
	 */
	transactionId: string;
	/**
	 * Paymentid
	 */
	paymentId: string;
	/**
	 * Clientid
	 */
	clientId: string;
	/**
	 * Action
	 */
	action: "BUY" | "SELL";
	/**
	 * Status
	 */
	status: "COMPLETED" | "PENDING";
	originToken: ThirdwebToken;
	/**
	 * Originamount
	 */
	originAmount: string;
	destinationToken: ThirdwebToken;
	/**
	 * Destinationamount
	 */
	destinationAmount: string;
	/**
	 * Sender
	 */
	sender: string;
	/**
	 * Receiver
	 */
	receiver: string;
	/**
	 * Type
	 */
	type: string;
	/**
	 * Transactions
	 */
	transactions: Array<ThirdwebTransactionReference>;
	purchaseData: ThirdwebPurchaseData;
};

/**
 * ThirdwebOnrampTransactionData
 */
export type ThirdwebOnrampTransactionData = {
	/**
	 * Id
	 */
	id: string;
	/**
	 * Onramp
	 */
	onramp: string;
	token: ThirdwebToken;
	/**
	 * Amount
	 */
	amount: string;
	/**
	 * Currency
	 */
	currency: string;
	/**
	 * Currencyamount
	 */
	currencyAmount: number;
	/**
	 * Receiver
	 */
	receiver: string;
	/**
	 * Status
	 */
	status: "PENDING" | "COMPLETED";
	purchaseData: ThirdwebPurchaseData;
};

/**
 * ThirdwebPurchaseData
 */
export type ThirdwebPurchaseData = {
	/**
	 * Userid
	 */
	userId: string;
};

/**
 * ThirdwebToken
 */
export type ThirdwebToken = {
	/**
	 * Chainid
	 */
	chainId: number;
	/**
	 * Address
	 */
	address: string;
	/**
	 * Symbol
	 */
	symbol: string;
	/**
	 * Name
	 */
	name: string;
	/**
	 * Decimals
	 */
	decimals: number;
	/**
	 * Priceusd
	 */
	priceUsd: number;
	/**
	 * Iconuri
	 */
	iconUri: string;
};

/**
 * ThirdwebTransactionReference
 */
export type ThirdwebTransactionReference = {
	/**
	 * Chainid
	 */
	chainId: number;
	/**
	 * Transactionhash
	 */
	transactionHash: string;
};

/**
 * ThirdwebWebhookPayload
 */
export type ThirdwebWebhookPayload = {
	/**
	 * Version
	 */
	version: number;
	/**
	 * Type
	 */
	type: string;
	/**
	 * Data
	 */
	data: ThirdwebOnchainTransactionData | ThirdwebOnrampTransactionData;
};

/**
 * TierResponse
 */
export type TierResponse = {
	/**
	 * Name
	 */
	name: string;
	/**
	 * Price Cents
	 */
	price_cents: number;
	/**
	 * Currency
	 */
	currency: string;
	/**
	 * Window 5H Credits
	 */
	window_5h_credits: number;
	/**
	 * Weekly Credits
	 */
	weekly_credits: number;
	/**
	 * Is Paid
	 */
	is_paid: boolean;
};

/**
 * TierSubscribers
 */
export type TierSubscribers = {
	/**
	 * Tier
	 */
	tier: string;
	/**
	 * Active Subscribers
	 */
	active_subscribers: number;
};

/**
 * TierSubscribersDay
 *
 * Active paid subscribers in one tier on a single day.
 */
export type TierSubscribersDay = {
	/**
	 * Date
	 */
	date: string;
	/**
	 * Tier
	 */
	tier: string;
	/**
	 * Active Subscribers
	 */
	active_subscribers: number;
};

/**
 * TokenPairResponse
 */
export type TokenPairResponse = {
	/**
	 * Access Token
	 */
	access_token: string;
	/**
	 * Refresh Token
	 */
	refresh_token: string;
	/**
	 * Token Type
	 */
	token_type?: string;
};

/**
 * TokenStats
 *
 * Stats about token usage for the current month.
 */
export type TokenStats = {
	/**
	 * Inference Calls
	 */
	inference_calls: number;
	/**
	 * Total Tokens
	 */
	total_tokens: number;
	/**
	 * Input Tokens
	 */
	input_tokens: number;
	/**
	 * Output Tokens
	 */
	output_tokens: number;
	/**
	 * Credits Used
	 */
	credits_used: number;
};

/**
 * TopupPackResponse
 */
export type TopupPackResponse = {
	/**
	 * Id
	 */
	id: string;
	/**
	 * Usd Credits
	 */
	usd_credits: number;
	/**
	 * Eur Charge
	 */
	eur_charge: number;
};

/**
 * TopupRequest
 */
export type TopupRequest = {
	/**
	 * Provider
	 */
	provider?: string;
	/**
	 * Amount
	 */
	amount?: number | null;
	/**
	 * Pack Id
	 */
	pack_id?: string | null;
	/**
	 * Redirect Base
	 */
	redirect_base?: string | null;
};

/**
 * UpdateProfileRequest
 */
export type UpdateProfileRequest = {
	/**
	 * Display Name
	 */
	display_name?: string | null;
	/**
	 * Monthly Extra Credit Cap
	 */
	monthly_extra_credit_cap?: number | null;
};

/**
 * UsageByEntity
 *
 * Usage statistics grouped by model or API key.
 */
export type UsageByEntity = {
	/**
	 * Name
	 */
	name: string;
	/**
	 * Calls
	 */
	calls: number;
	/**
	 * Total Tokens
	 */
	total_tokens: number;
	/**
	 * Cost
	 */
	cost: number;
};

/**
 * UsageStats
 *
 * Detailed usage statistics for a date range.
 */
export type UsageStats = {
	/**
	 * Inference Calls
	 */
	inference_calls: number;
	/**
	 * Input Tokens
	 */
	input_tokens: number;
	/**
	 * Output Tokens
	 */
	output_tokens: number;
	/**
	 * Total Tokens
	 */
	total_tokens: number;
	/**
	 * Cost
	 */
	cost: number;
	/**
	 * Daily Usage
	 */
	daily_usage: {
		[key: string]: DailyTokens;
	};
	/**
	 * Usage By Model
	 */
	usage_by_model: Array<UsageByEntity>;
	/**
	 * Usage By Api Key
	 */
	usage_by_api_key: Array<UsageByEntity>;
};

/**
 * UsersWindow
 *
 * Rolling window for active-user counts: DAU (day), WAU (week), MAU (month).
 */
export type UsersWindow = "day" | "week" | "month";

/**
 * ValidationError
 */
export type ValidationError = {
	/**
	 * Location
	 */
	loc: Array<string | number>;
	/**
	 * Message
	 */
	msg: string;
	/**
	 * Error Type
	 */
	type: string;
};

/**
 * VerifyMagicLinkRequest
 */
export type VerifyMagicLinkRequest = {
	/**
	 * Token
	 */
	token?: string | null;
	/**
	 * Email
	 */
	email?: string | null;
	/**
	 * Code
	 */
	code?: string | null;
};

/**
 * VoucherAddCreditsRequest
 */
export type VoucherAddCreditsRequest = {
	/**
	 * Amount
	 */
	amount: number;
	/**
	 * Expired At
	 */
	expired_at?: string | null;
	chain?: LibertaiChain | null;
	/**
	 * Address
	 */
	address?: string | null;
	/**
	 * Email
	 */
	email?: string | null;
};

/**
 * VoucherChangeExpireRequest
 */
export type VoucherChangeExpireRequest = {
	/**
	 * Voucher Id
	 */
	voucher_id: string;
	/**
	 * Expired At
	 */
	expired_at: string | null;
};

/**
 * VoucherCreditsResponse
 */
export type VoucherCreditsResponse = {
	/**
	 * Id
	 */
	id: string;
	/**
	 * Address
	 */
	address: string | null;
	/**
	 * Amount
	 */
	amount: number;
	/**
	 * Amount Left
	 */
	amount_left: number;
	/**
	 * Expired At
	 */
	expired_at: string | null;
	/**
	 * Created At
	 */
	created_at: string;
	/**
	 * Is Active
	 */
	is_active: boolean;
};

/**
 * WalletChallengeRequest
 */
export type WalletChallengeRequest = {
	/**
	 * Address
	 */
	address: string;
};

/**
 * WalletChallengeResponse
 */
export type WalletChallengeResponse = {
	/**
	 * Message
	 */
	message: string;
};

/**
 * WalletVerifyRequest
 */
export type WalletVerifyRequest = {
	/**
	 * Address
	 */
	address: string;
	/**
	 * Signature
	 */
	signature: string;
};

export type GetAuthMessageAuthMessagePostData = {
	body: AuthMessageRequest;
	path?: never;
	query?: never;
	url: "/auth/message";
};

export type GetAuthMessageAuthMessagePostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetAuthMessageAuthMessagePostError =
	GetAuthMessageAuthMessagePostErrors[keyof GetAuthMessageAuthMessagePostErrors];

export type GetAuthMessageAuthMessagePostResponses = {
	/**
	 * Successful Response
	 */
	200: AuthMessageResponse;
};

export type GetAuthMessageAuthMessagePostResponse =
	GetAuthMessageAuthMessagePostResponses[keyof GetAuthMessageAuthMessagePostResponses];

export type LoginWithWalletAuthLoginPostData = {
	body: AuthLoginRequest;
	path?: never;
	query?: never;
	url: "/auth/login";
};

export type LoginWithWalletAuthLoginPostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type LoginWithWalletAuthLoginPostError =
	LoginWithWalletAuthLoginPostErrors[keyof LoginWithWalletAuthLoginPostErrors];

export type LoginWithWalletAuthLoginPostResponses = {
	/**
	 * Successful Response
	 */
	200: AuthLoginResponse;
};

export type LoginWithWalletAuthLoginPostResponse =
	LoginWithWalletAuthLoginPostResponses[keyof LoginWithWalletAuthLoginPostResponses];

export type CheckAuthStatusAuthStatusGetData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/auth/status";
};

export type CheckAuthStatusAuthStatusGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type CheckAuthStatusAuthStatusGetError =
	CheckAuthStatusAuthStatusGetErrors[keyof CheckAuthStatusAuthStatusGetErrors];

export type CheckAuthStatusAuthStatusGetResponses = {
	/**
	 * Successful Response
	 */
	200: AuthStatusResponse;
};

export type CheckAuthStatusAuthStatusGetResponse =
	CheckAuthStatusAuthStatusGetResponses[keyof CheckAuthStatusAuthStatusGetResponses];

export type GetMeAuthMeGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query?: never;
	url: "/auth/me";
};

export type GetMeAuthMeGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetMeAuthMeGetError = GetMeAuthMeGetErrors[keyof GetMeAuthMeGetErrors];

export type GetMeAuthMeGetResponses = {
	/**
	 * Successful Response
	 */
	200: CurrentUserResponse;
};

export type GetMeAuthMeGetResponse = GetMeAuthMeGetResponses[keyof GetMeAuthMeGetResponses];

export type UpdateMeAuthMePatchData = {
	body: UpdateProfileRequest;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query?: never;
	url: "/auth/me";
};

export type UpdateMeAuthMePatchErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type UpdateMeAuthMePatchError = UpdateMeAuthMePatchErrors[keyof UpdateMeAuthMePatchErrors];

export type UpdateMeAuthMePatchResponses = {
	/**
	 * Successful Response
	 */
	200: CurrentUserResponse;
};

export type UpdateMeAuthMePatchResponse = UpdateMeAuthMePatchResponses[keyof UpdateMeAuthMePatchResponses];

export type WalletChallengeAuthWalletChallengePostData = {
	body: WalletChallengeRequest;
	path?: never;
	query?: never;
	url: "/auth/wallet/challenge";
};

export type WalletChallengeAuthWalletChallengePostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type WalletChallengeAuthWalletChallengePostError =
	WalletChallengeAuthWalletChallengePostErrors[keyof WalletChallengeAuthWalletChallengePostErrors];

export type WalletChallengeAuthWalletChallengePostResponses = {
	/**
	 * Successful Response
	 */
	200: WalletChallengeResponse;
};

export type WalletChallengeAuthWalletChallengePostResponse =
	WalletChallengeAuthWalletChallengePostResponses[keyof WalletChallengeAuthWalletChallengePostResponses];

export type WalletVerifyAuthWalletVerifyPostData = {
	body: WalletVerifyRequest;
	path?: never;
	query?: never;
	url: "/auth/wallet/verify";
};

export type WalletVerifyAuthWalletVerifyPostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type WalletVerifyAuthWalletVerifyPostError =
	WalletVerifyAuthWalletVerifyPostErrors[keyof WalletVerifyAuthWalletVerifyPostErrors];

export type WalletVerifyAuthWalletVerifyPostResponses = {
	/**
	 * Successful Response
	 */
	200: TokenPairResponse;
};

export type WalletVerifyAuthWalletVerifyPostResponse =
	WalletVerifyAuthWalletVerifyPostResponses[keyof WalletVerifyAuthWalletVerifyPostResponses];

export type LoginEmailAuthLoginEmailPostData = {
	body: EmailLoginRequest;
	path?: never;
	query?: never;
	url: "/auth/login/email";
};

export type LoginEmailAuthLoginEmailPostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type LoginEmailAuthLoginEmailPostError =
	LoginEmailAuthLoginEmailPostErrors[keyof LoginEmailAuthLoginEmailPostErrors];

export type LoginEmailAuthLoginEmailPostResponses = {
	/**
	 * Successful Response
	 */
	204: void;
};

export type LoginEmailAuthLoginEmailPostResponse =
	LoginEmailAuthLoginEmailPostResponses[keyof LoginEmailAuthLoginEmailPostResponses];

export type VerifyMagicLinkRouteAuthVerifyMagicLinkPostData = {
	body: VerifyMagicLinkRequest;
	path?: never;
	query?: never;
	url: "/auth/verify-magic-link";
};

export type VerifyMagicLinkRouteAuthVerifyMagicLinkPostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type VerifyMagicLinkRouteAuthVerifyMagicLinkPostError =
	VerifyMagicLinkRouteAuthVerifyMagicLinkPostErrors[keyof VerifyMagicLinkRouteAuthVerifyMagicLinkPostErrors];

export type VerifyMagicLinkRouteAuthVerifyMagicLinkPostResponses = {
	/**
	 * Successful Response
	 */
	200: TokenPairResponse;
};

export type VerifyMagicLinkRouteAuthVerifyMagicLinkPostResponse =
	VerifyMagicLinkRouteAuthVerifyMagicLinkPostResponses[keyof VerifyMagicLinkRouteAuthVerifyMagicLinkPostResponses];

export type OauthStartAuthOauthProviderGetData = {
	body?: never;
	path: {
		/**
		 * Provider
		 */
		provider: string;
	};
	query?: {
		/**
		 * Redirect Base
		 */
		redirect_base?: string | null;
	};
	url: "/auth/oauth/{provider}";
};

export type OauthStartAuthOauthProviderGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type OauthStartAuthOauthProviderGetError =
	OauthStartAuthOauthProviderGetErrors[keyof OauthStartAuthOauthProviderGetErrors];

export type OauthStartAuthOauthProviderGetResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type OauthCallbackAuthOauthProviderCallbackGetData = {
	body?: never;
	path: {
		/**
		 * Provider
		 */
		provider: string;
	};
	query: {
		/**
		 * Code
		 */
		code: string;
		/**
		 * State
		 */
		state: string;
	};
	url: "/auth/oauth/{provider}/callback";
};

export type OauthCallbackAuthOauthProviderCallbackGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type OauthCallbackAuthOauthProviderCallbackGetError =
	OauthCallbackAuthOauthProviderCallbackGetErrors[keyof OauthCallbackAuthOauthProviderCallbackGetErrors];

export type OauthCallbackAuthOauthProviderCallbackGetResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type ExchangeCodeAuthExchangePostData = {
	body: ExchangeRequest;
	path?: never;
	query?: never;
	url: "/auth/exchange";
};

export type ExchangeCodeAuthExchangePostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type ExchangeCodeAuthExchangePostError =
	ExchangeCodeAuthExchangePostErrors[keyof ExchangeCodeAuthExchangePostErrors];

export type ExchangeCodeAuthExchangePostResponses = {
	/**
	 * Successful Response
	 */
	200: TokenPairResponse;
};

export type ExchangeCodeAuthExchangePostResponse =
	ExchangeCodeAuthExchangePostResponses[keyof ExchangeCodeAuthExchangePostResponses];

export type CliCodeAuthCliCodePostData = {
	body: CliCodeRequest;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query?: never;
	url: "/auth/cli/code";
};

export type CliCodeAuthCliCodePostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type CliCodeAuthCliCodePostError = CliCodeAuthCliCodePostErrors[keyof CliCodeAuthCliCodePostErrors];

export type CliCodeAuthCliCodePostResponses = {
	/**
	 * Successful Response
	 */
	200: CliCodeResponse;
};

export type CliCodeAuthCliCodePostResponse = CliCodeAuthCliCodePostResponses[keyof CliCodeAuthCliCodePostResponses];

export type RefreshTokensAuthRefreshPostData = {
	body: RefreshRequest;
	path?: never;
	query?: never;
	url: "/auth/refresh";
};

export type RefreshTokensAuthRefreshPostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type RefreshTokensAuthRefreshPostError =
	RefreshTokensAuthRefreshPostErrors[keyof RefreshTokensAuthRefreshPostErrors];

export type RefreshTokensAuthRefreshPostResponses = {
	/**
	 * Successful Response
	 */
	200: TokenPairResponse;
};

export type RefreshTokensAuthRefreshPostResponse =
	RefreshTokensAuthRefreshPostResponses[keyof RefreshTokensAuthRefreshPostResponses];

export type LogoutAuthLogoutPostData = {
	body?: LogoutRequest;
	path?: never;
	query?: never;
	url: "/auth/logout";
};

export type LogoutAuthLogoutPostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type LogoutAuthLogoutPostError = LogoutAuthLogoutPostErrors[keyof LogoutAuthLogoutPostErrors];

export type LogoutAuthLogoutPostResponses = {
	/**
	 * Successful Response
	 */
	204: void;
};

export type LogoutAuthLogoutPostResponse = LogoutAuthLogoutPostResponses[keyof LogoutAuthLogoutPostResponses];

export type LinkWalletRouteAuthLinkWalletPostData = {
	body: WalletVerifyRequest;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query?: never;
	url: "/auth/link/wallet";
};

export type LinkWalletRouteAuthLinkWalletPostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type LinkWalletRouteAuthLinkWalletPostError =
	LinkWalletRouteAuthLinkWalletPostErrors[keyof LinkWalletRouteAuthLinkWalletPostErrors];

export type LinkWalletRouteAuthLinkWalletPostResponses = {
	/**
	 * Successful Response
	 */
	204: void;
};

export type LinkWalletRouteAuthLinkWalletPostResponse =
	LinkWalletRouteAuthLinkWalletPostResponses[keyof LinkWalletRouteAuthLinkWalletPostResponses];

export type ProcessBaseLtaiTransactionsCreditsLtaiBaseProcessPostData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/credits/ltai/base/process";
};

export type ProcessBaseLtaiTransactionsCreditsLtaiBaseProcessPostResponses = {
	/**
	 * Response Process Base Ltai Transactions Credits Ltai Base Process Post
	 *
	 * Successful Response
	 */
	200: Array<string>;
};

export type ProcessBaseLtaiTransactionsCreditsLtaiBaseProcessPostResponse =
	ProcessBaseLtaiTransactionsCreditsLtaiBaseProcessPostResponses[keyof ProcessBaseLtaiTransactionsCreditsLtaiBaseProcessPostResponses];

export type ProcessSolanaLtaiTransactionsCreditsLtaiSolanaProcessPostData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/credits/ltai/solana/process";
};

export type ProcessSolanaLtaiTransactionsCreditsLtaiSolanaProcessPostResponses = {
	/**
	 * Response Process Solana Ltai Transactions Credits Ltai Solana Process Post
	 *
	 * Successful Response
	 */
	200: Array<string>;
};

export type ProcessSolanaLtaiTransactionsCreditsLtaiSolanaProcessPostResponse =
	ProcessSolanaLtaiTransactionsCreditsLtaiSolanaProcessPostResponses[keyof ProcessSolanaLtaiTransactionsCreditsLtaiSolanaProcessPostResponses];

export type ThirdwebWebhookCreditsThirdwebWebhookPostData = {
	body: ThirdwebWebhookPayload;
	headers?: {
		/**
		 * X-Pay-Signature
		 */
		"X-Pay-Signature"?: string;
		/**
		 * X-Pay-Timestamp
		 */
		"X-Pay-Timestamp"?: string;
	};
	path?: never;
	query?: never;
	url: "/credits/thirdweb/webhook";
};

export type ThirdwebWebhookCreditsThirdwebWebhookPostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type ThirdwebWebhookCreditsThirdwebWebhookPostError =
	ThirdwebWebhookCreditsThirdwebWebhookPostErrors[keyof ThirdwebWebhookCreditsThirdwebWebhookPostErrors];

export type ThirdwebWebhookCreditsThirdwebWebhookPostResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type UpdateExpiredCreditTransactionsCreditsUpdateExpiredPostData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/credits/update-expired";
};

export type UpdateExpiredCreditTransactionsCreditsUpdateExpiredPostResponses = {
	/**
	 * Successful Response
	 */
	200: ExpiredCreditTransactionsResponse;
};

export type UpdateExpiredCreditTransactionsCreditsUpdateExpiredPostResponse =
	UpdateExpiredCreditTransactionsCreditsUpdateExpiredPostResponses[keyof UpdateExpiredCreditTransactionsCreditsUpdateExpiredPostResponses];

export type GetUserBalanceCreditsBalanceGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query?: never;
	url: "/credits/balance";
};

export type GetUserBalanceCreditsBalanceGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetUserBalanceCreditsBalanceGetError =
	GetUserBalanceCreditsBalanceGetErrors[keyof GetUserBalanceCreditsBalanceGetErrors];

export type GetUserBalanceCreditsBalanceGetResponses = {
	/**
	 * Successful Response
	 */
	200: CreditBalanceResponse;
};

export type GetUserBalanceCreditsBalanceGetResponse =
	GetUserBalanceCreditsBalanceGetResponses[keyof GetUserBalanceCreditsBalanceGetResponses];

export type GetTransactionHistoryCreditsTransactionsGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query?: never;
	url: "/credits/transactions";
};

export type GetTransactionHistoryCreditsTransactionsGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetTransactionHistoryCreditsTransactionsGetError =
	GetTransactionHistoryCreditsTransactionsGetErrors[keyof GetTransactionHistoryCreditsTransactionsGetErrors];

export type GetTransactionHistoryCreditsTransactionsGetResponses = {
	/**
	 * Successful Response
	 */
	200: CreditTransactionsResponse;
};

export type GetTransactionHistoryCreditsTransactionsGetResponse =
	GetTransactionHistoryCreditsTransactionsGetResponses[keyof GetTransactionHistoryCreditsTransactionsGetResponses];

export type GetVouchersCreditsVouchersGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query?: {
		/**
		 * Chain
		 */
		chain?: LibertaiChain | null;
		/**
		 * Address
		 */
		address?: string | null;
		/**
		 * Email
		 */
		email?: string | null;
	};
	url: "/credits/vouchers";
};

export type GetVouchersCreditsVouchersGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetVouchersCreditsVouchersGetError =
	GetVouchersCreditsVouchersGetErrors[keyof GetVouchersCreditsVouchersGetErrors];

export type GetVouchersCreditsVouchersGetResponses = {
	/**
	 * Response Get Vouchers Credits Vouchers Get
	 *
	 * Successful Response
	 */
	200: Array<VoucherCreditsResponse>;
};

export type GetVouchersCreditsVouchersGetResponse =
	GetVouchersCreditsVouchersGetResponses[keyof GetVouchersCreditsVouchersGetResponses];

export type AddVoucherCreditsCreditsVouchersPostData = {
	body: VoucherAddCreditsRequest;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query?: never;
	url: "/credits/vouchers";
};

export type AddVoucherCreditsCreditsVouchersPostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type AddVoucherCreditsCreditsVouchersPostError =
	AddVoucherCreditsCreditsVouchersPostErrors[keyof AddVoucherCreditsCreditsVouchersPostErrors];

export type AddVoucherCreditsCreditsVouchersPostResponses = {
	/**
	 * Response Add Voucher Credits Credits Vouchers Post
	 *
	 * Successful Response
	 */
	200: boolean;
};

export type AddVoucherCreditsCreditsVouchersPostResponse =
	AddVoucherCreditsCreditsVouchersPostResponses[keyof AddVoucherCreditsCreditsVouchersPostResponses];

export type ChangeVoucherExpirationCreditsVoucherExpirationPostData = {
	body: VoucherChangeExpireRequest;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query?: never;
	url: "/credits/voucher/expiration";
};

export type ChangeVoucherExpirationCreditsVoucherExpirationPostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type ChangeVoucherExpirationCreditsVoucherExpirationPostError =
	ChangeVoucherExpirationCreditsVoucherExpirationPostErrors[keyof ChangeVoucherExpirationCreditsVoucherExpirationPostErrors];

export type ChangeVoucherExpirationCreditsVoucherExpirationPostResponses = {
	/**
	 * Response Change Voucher Expiration Credits Voucher Expiration Post
	 *
	 * Successful Response
	 */
	200: boolean;
};

export type ChangeVoucherExpirationCreditsVoucherExpirationPostResponse =
	ChangeVoucherExpirationCreditsVoucherExpirationPostResponses[keyof ChangeVoucherExpirationCreditsVoucherExpirationPostResponses];

export type GetApiKeysApiKeysGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query?: never;
	url: "/api-keys";
};

export type GetApiKeysApiKeysGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetApiKeysApiKeysGetError = GetApiKeysApiKeysGetErrors[keyof GetApiKeysApiKeysGetErrors];

export type GetApiKeysApiKeysGetResponses = {
	/**
	 * Successful Response
	 */
	200: ApiKeyListResponse;
};

export type GetApiKeysApiKeysGetResponse = GetApiKeysApiKeysGetResponses[keyof GetApiKeysApiKeysGetResponses];

export type CreateApiKeyApiKeysPostData = {
	body: ApiKeyCreate;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query?: never;
	url: "/api-keys";
};

export type CreateApiKeyApiKeysPostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type CreateApiKeyApiKeysPostError = CreateApiKeyApiKeysPostErrors[keyof CreateApiKeyApiKeysPostErrors];

export type CreateApiKeyApiKeysPostResponses = {
	/**
	 * Successful Response
	 */
	200: FullApiKey;
};

export type CreateApiKeyApiKeysPostResponse = CreateApiKeyApiKeysPostResponses[keyof CreateApiKeyApiKeysPostResponses];

export type GetChatApiKeyApiKeysChatGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query?: never;
	url: "/api-keys/chat";
};

export type GetChatApiKeyApiKeysChatGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetChatApiKeyApiKeysChatGetError =
	GetChatApiKeyApiKeysChatGetErrors[keyof GetChatApiKeyApiKeysChatGetErrors];

export type GetChatApiKeyApiKeysChatGetResponses = {
	/**
	 * Successful Response
	 */
	200: ChatApiKeyResponse;
};

export type GetChatApiKeyApiKeysChatGetResponse =
	GetChatApiKeyApiKeysChatGetResponses[keyof GetChatApiKeyApiKeysChatGetResponses];

export type GetCliApiKeysApiKeysCliGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query?: never;
	url: "/api-keys/cli";
};

export type GetCliApiKeysApiKeysCliGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetCliApiKeysApiKeysCliGetError = GetCliApiKeysApiKeysCliGetErrors[keyof GetCliApiKeysApiKeysCliGetErrors];

export type GetCliApiKeysApiKeysCliGetResponses = {
	/**
	 * Response Get Cli Api Keys Api Keys Cli Get
	 *
	 * Successful Response
	 */
	200: Array<ApiKey>;
};

export type GetCliApiKeysApiKeysCliGetResponse =
	GetCliApiKeysApiKeysCliGetResponses[keyof GetCliApiKeysApiKeysCliGetResponses];

export type CreateCliApiKeyApiKeysCliPostData = {
	body: CliApiKeyCreate;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query?: never;
	url: "/api-keys/cli";
};

export type CreateCliApiKeyApiKeysCliPostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type CreateCliApiKeyApiKeysCliPostError =
	CreateCliApiKeyApiKeysCliPostErrors[keyof CreateCliApiKeyApiKeysCliPostErrors];

export type CreateCliApiKeyApiKeysCliPostResponses = {
	/**
	 * Successful Response
	 */
	200: FullApiKey;
};

export type CreateCliApiKeyApiKeysCliPostResponse =
	CreateCliApiKeyApiKeysCliPostResponses[keyof CreateCliApiKeyApiKeysCliPostResponses];

export type DeleteApiKeyApiKeysKeyIdDeleteData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path: {
		/**
		 * Key Id
		 */
		key_id: string;
	};
	query?: never;
	url: "/api-keys/{key_id}";
};

export type DeleteApiKeyApiKeysKeyIdDeleteErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type DeleteApiKeyApiKeysKeyIdDeleteError =
	DeleteApiKeyApiKeysKeyIdDeleteErrors[keyof DeleteApiKeyApiKeysKeyIdDeleteErrors];

export type DeleteApiKeyApiKeysKeyIdDeleteResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type UpdateApiKeyApiKeysKeyIdPutData = {
	body: ApiKeyUpdate;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path: {
		/**
		 * Key Id
		 */
		key_id: string;
	};
	query?: never;
	url: "/api-keys/{key_id}";
};

export type UpdateApiKeyApiKeysKeyIdPutErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type UpdateApiKeyApiKeysKeyIdPutError =
	UpdateApiKeyApiKeysKeyIdPutErrors[keyof UpdateApiKeyApiKeysKeyIdPutErrors];

export type UpdateApiKeyApiKeysKeyIdPutResponses = {
	/**
	 * Successful Response
	 */
	200: ApiKey;
};

export type UpdateApiKeyApiKeysKeyIdPutResponse =
	UpdateApiKeyApiKeysKeyIdPutResponses[keyof UpdateApiKeyApiKeysKeyIdPutResponses];

export type RegisterInferenceCallApiKeysAdminUsagePostData = {
	/**
	 * Usage Log
	 */
	body: TextInferenceCallData | ImageInferenceCallData | AudioInferenceCallData;
	path?: never;
	query?: never;
	url: "/api-keys/admin/usage";
};

export type RegisterInferenceCallApiKeysAdminUsagePostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type RegisterInferenceCallApiKeysAdminUsagePostError =
	RegisterInferenceCallApiKeysAdminUsagePostErrors[keyof RegisterInferenceCallApiKeysAdminUsagePostErrors];

export type RegisterInferenceCallApiKeysAdminUsagePostResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type GetAdminAllApiKeysApiKeysAdminListGetData = {
	body?: never;
	headers: {
		/**
		 * X-Admin-Token
		 */
		"x-admin-token": string;
	};
	path?: never;
	query?: never;
	url: "/api-keys/admin/list";
};

export type GetAdminAllApiKeysApiKeysAdminListGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetAdminAllApiKeysApiKeysAdminListGetError =
	GetAdminAllApiKeysApiKeysAdminListGetErrors[keyof GetAdminAllApiKeysApiKeysAdminListGetErrors];

export type GetAdminAllApiKeysApiKeysAdminListGetResponses = {
	/**
	 * Successful Response
	 */
	200: ApiKeyAdminListResponse;
};

export type GetAdminAllApiKeysApiKeysAdminListGetResponse =
	GetAdminAllApiKeysApiKeysAdminListGetResponses[keyof GetAdminAllApiKeysApiKeysAdminListGetResponses];

export type GetDashboardStatsStatsDashboardGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query?: never;
	url: "/stats/dashboard";
};

export type GetDashboardStatsStatsDashboardGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetDashboardStatsStatsDashboardGetError =
	GetDashboardStatsStatsDashboardGetErrors[keyof GetDashboardStatsStatsDashboardGetErrors];

export type GetDashboardStatsStatsDashboardGetResponses = {
	/**
	 * Successful Response
	 */
	200: DashboardStats;
};

export type GetDashboardStatsStatsDashboardGetResponse =
	GetDashboardStatsStatsDashboardGetResponses[keyof GetDashboardStatsStatsDashboardGetResponses];

export type GetUsageStatsStatsUsageGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query: {
		/**
		 * Start Date
		 *
		 * Start date in format YYYY-MM-DD
		 */
		start_date: string;
		/**
		 * End Date
		 *
		 * End date in format YYYY-MM-DD
		 */
		end_date: string;
	};
	url: "/stats/usage";
};

export type GetUsageStatsStatsUsageGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetUsageStatsStatsUsageGetError = GetUsageStatsStatsUsageGetErrors[keyof GetUsageStatsStatsUsageGetErrors];

export type GetUsageStatsStatsUsageGetResponses = {
	/**
	 * Successful Response
	 */
	200: UsageStats;
};

export type GetUsageStatsStatsUsageGetResponse =
	GetUsageStatsStatsUsageGetResponses[keyof GetUsageStatsStatsUsageGetResponses];

export type GetChatCallsStatsStatsGlobalChatCallsGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query: {
		/**
		 * Start Date
		 *
		 * Start date in format YYYY-MM-DD
		 */
		start_date: string;
		/**
		 * End Date
		 *
		 * End date in format YYYY-MM-DD
		 */
		end_date: string;
	};
	url: "/stats/global/chat/calls";
};

export type GetChatCallsStatsStatsGlobalChatCallsGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetChatCallsStatsStatsGlobalChatCallsGetError =
	GetChatCallsStatsStatsGlobalChatCallsGetErrors[keyof GetChatCallsStatsStatsGlobalChatCallsGetErrors];

export type GetChatCallsStatsStatsGlobalChatCallsGetResponses = {
	/**
	 * Successful Response
	 */
	200: GlobalChatCallsStats;
};

export type GetChatCallsStatsStatsGlobalChatCallsGetResponse =
	GetChatCallsStatsStatsGlobalChatCallsGetResponses[keyof GetChatCallsStatsStatsGlobalChatCallsGetResponses];

export type GetChatTokensStatsStatsGlobalChatTokensGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query: {
		/**
		 * Start Date
		 *
		 * Start date in format YYYY-MM-DD
		 */
		start_date: string;
		/**
		 * End Date
		 *
		 * End date in format YYYY-MM-DD
		 */
		end_date: string;
	};
	url: "/stats/global/chat/tokens";
};

export type GetChatTokensStatsStatsGlobalChatTokensGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetChatTokensStatsStatsGlobalChatTokensGetError =
	GetChatTokensStatsStatsGlobalChatTokensGetErrors[keyof GetChatTokensStatsStatsGlobalChatTokensGetErrors];

export type GetChatTokensStatsStatsGlobalChatTokensGetResponses = {
	/**
	 * Successful Response
	 */
	200: GlobalChatTokensStats;
};

export type GetChatTokensStatsStatsGlobalChatTokensGetResponse =
	GetChatTokensStatsStatsGlobalChatTokensGetResponses[keyof GetChatTokensStatsStatsGlobalChatTokensGetResponses];

export type GetChatUsersStatsStatsGlobalChatUsersGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query: {
		/**
		 * Start Date
		 *
		 * Start date in format YYYY-MM-DD
		 */
		start_date: string;
		/**
		 * End Date
		 *
		 * End date in format YYYY-MM-DD
		 */
		end_date: string;
		/**
		 * Rolling window: day (DAU), week (WAU), month (MAU)
		 */
		window?: UsersWindow;
	};
	url: "/stats/global/chat/users";
};

export type GetChatUsersStatsStatsGlobalChatUsersGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetChatUsersStatsStatsGlobalChatUsersGetError =
	GetChatUsersStatsStatsGlobalChatUsersGetErrors[keyof GetChatUsersStatsStatsGlobalChatUsersGetErrors];

export type GetChatUsersStatsStatsGlobalChatUsersGetResponses = {
	/**
	 * Successful Response
	 */
	200: GlobalUsersStats;
};

export type GetChatUsersStatsStatsGlobalChatUsersGetResponse =
	GetChatUsersStatsStatsGlobalChatUsersGetResponses[keyof GetChatUsersStatsStatsGlobalChatUsersGetResponses];

export type GetLatestSubscribersStatsGlobalSubscriptionsLatestGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query?: {
		/**
		 * Limit
		 *
		 * Max rows to return; omit for all matching
		 */
		limit?: number | null;
		/**
		 * Status
		 *
		 * Comma-separated subscription statuses; omitted = all except pending
		 */
		status?: string | null;
	};
	url: "/stats/global/subscriptions/latest";
};

export type GetLatestSubscribersStatsGlobalSubscriptionsLatestGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetLatestSubscribersStatsGlobalSubscriptionsLatestGetError =
	GetLatestSubscribersStatsGlobalSubscriptionsLatestGetErrors[keyof GetLatestSubscribersStatsGlobalSubscriptionsLatestGetErrors];

export type GetLatestSubscribersStatsGlobalSubscriptionsLatestGetResponses = {
	/**
	 * Successful Response
	 */
	200: GlobalLatestSubscribersStats;
};

export type GetLatestSubscribersStatsGlobalSubscriptionsLatestGetResponse =
	GetLatestSubscribersStatsGlobalSubscriptionsLatestGetResponses[keyof GetLatestSubscribersStatsGlobalSubscriptionsLatestGetResponses];

export type GetSubscriptionActivityStatsGlobalSubscriptionsActivityGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query?: {
		/**
		 * Limit
		 *
		 * Number of recent activity events to return
		 */
		limit?: number;
		/**
		 * Types
		 *
		 * Comma-separated activity types; omitted = all
		 */
		types?: string | null;
	};
	url: "/stats/global/subscriptions/activity";
};

export type GetSubscriptionActivityStatsGlobalSubscriptionsActivityGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetSubscriptionActivityStatsGlobalSubscriptionsActivityGetError =
	GetSubscriptionActivityStatsGlobalSubscriptionsActivityGetErrors[keyof GetSubscriptionActivityStatsGlobalSubscriptionsActivityGetErrors];

export type GetSubscriptionActivityStatsGlobalSubscriptionsActivityGetResponses = {
	/**
	 * Successful Response
	 */
	200: GlobalSubscriptionActivityStats;
};

export type GetSubscriptionActivityStatsGlobalSubscriptionsActivityGetResponse =
	GetSubscriptionActivityStatsGlobalSubscriptionsActivityGetResponses[keyof GetSubscriptionActivityStatsGlobalSubscriptionsActivityGetResponses];

export type GetSubscriptionsRevenueStatsGlobalSubscriptionsRevenueGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query: {
		/**
		 * Start Date
		 *
		 * Start date in format YYYY-MM-DD
		 */
		start_date: string;
		/**
		 * End Date
		 *
		 * End date in format YYYY-MM-DD
		 */
		end_date: string;
	};
	url: "/stats/global/subscriptions/revenue";
};

export type GetSubscriptionsRevenueStatsGlobalSubscriptionsRevenueGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetSubscriptionsRevenueStatsGlobalSubscriptionsRevenueGetError =
	GetSubscriptionsRevenueStatsGlobalSubscriptionsRevenueGetErrors[keyof GetSubscriptionsRevenueStatsGlobalSubscriptionsRevenueGetErrors];

export type GetSubscriptionsRevenueStatsGlobalSubscriptionsRevenueGetResponses = {
	/**
	 * Successful Response
	 */
	200: GlobalSubscriptionsRevenueStats;
};

export type GetSubscriptionsRevenueStatsGlobalSubscriptionsRevenueGetResponse =
	GetSubscriptionsRevenueStatsGlobalSubscriptionsRevenueGetResponses[keyof GetSubscriptionsRevenueStatsGlobalSubscriptionsRevenueGetResponses];

export type GetSubscriptionsChurnStatsGlobalSubscriptionsChurnGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query: {
		/**
		 * Start Date
		 *
		 * Start date in format YYYY-MM-DD
		 */
		start_date: string;
		/**
		 * End Date
		 *
		 * End date in format YYYY-MM-DD
		 */
		end_date: string;
	};
	url: "/stats/global/subscriptions/churn";
};

export type GetSubscriptionsChurnStatsGlobalSubscriptionsChurnGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetSubscriptionsChurnStatsGlobalSubscriptionsChurnGetError =
	GetSubscriptionsChurnStatsGlobalSubscriptionsChurnGetErrors[keyof GetSubscriptionsChurnStatsGlobalSubscriptionsChurnGetErrors];

export type GetSubscriptionsChurnStatsGlobalSubscriptionsChurnGetResponses = {
	/**
	 * Successful Response
	 */
	200: GlobalSubscriptionsChurnStats;
};

export type GetSubscriptionsChurnStatsGlobalSubscriptionsChurnGetResponse =
	GetSubscriptionsChurnStatsGlobalSubscriptionsChurnGetResponses[keyof GetSubscriptionsChurnStatsGlobalSubscriptionsChurnGetResponses];

export type GetInferenceCallsStatsStatsGlobalKeyTypeCallsGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path: {
		key_type: InferenceKeyType;
	};
	query: {
		/**
		 * Start Date
		 *
		 * Start date in format YYYY-MM-DD
		 */
		start_date: string;
		/**
		 * End Date
		 *
		 * End date in format YYYY-MM-DD
		 */
		end_date: string;
	};
	url: "/stats/global/{key_type}/calls";
};

export type GetInferenceCallsStatsStatsGlobalKeyTypeCallsGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetInferenceCallsStatsStatsGlobalKeyTypeCallsGetError =
	GetInferenceCallsStatsStatsGlobalKeyTypeCallsGetErrors[keyof GetInferenceCallsStatsStatsGlobalKeyTypeCallsGetErrors];

export type GetInferenceCallsStatsStatsGlobalKeyTypeCallsGetResponses = {
	/**
	 * Successful Response
	 */
	200: GlobalApiStats;
};

export type GetInferenceCallsStatsStatsGlobalKeyTypeCallsGetResponse =
	GetInferenceCallsStatsStatsGlobalKeyTypeCallsGetResponses[keyof GetInferenceCallsStatsStatsGlobalKeyTypeCallsGetResponses];

export type GetInferenceTokensStatsStatsGlobalKeyTypeTokensGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path: {
		key_type: InferenceKeyType;
	};
	query: {
		/**
		 * Start Date
		 *
		 * Start date in format YYYY-MM-DD
		 */
		start_date: string;
		/**
		 * End Date
		 *
		 * End date in format YYYY-MM-DD
		 */
		end_date: string;
	};
	url: "/stats/global/{key_type}/tokens";
};

export type GetInferenceTokensStatsStatsGlobalKeyTypeTokensGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetInferenceTokensStatsStatsGlobalKeyTypeTokensGetError =
	GetInferenceTokensStatsStatsGlobalKeyTypeTokensGetErrors[keyof GetInferenceTokensStatsStatsGlobalKeyTypeTokensGetErrors];

export type GetInferenceTokensStatsStatsGlobalKeyTypeTokensGetResponses = {
	/**
	 * Successful Response
	 */
	200: GlobalTokensStats;
};

export type GetInferenceTokensStatsStatsGlobalKeyTypeTokensGetResponse =
	GetInferenceTokensStatsStatsGlobalKeyTypeTokensGetResponses[keyof GetInferenceTokensStatsStatsGlobalKeyTypeTokensGetResponses];

export type GetInferenceCreditsStatsStatsGlobalKeyTypeCreditsGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path: {
		key_type: InferenceKeyType;
	};
	query: {
		/**
		 * Start Date
		 *
		 * Start date in format YYYY-MM-DD
		 */
		start_date: string;
		/**
		 * End Date
		 *
		 * End date in format YYYY-MM-DD
		 */
		end_date: string;
	};
	url: "/stats/global/{key_type}/credits";
};

export type GetInferenceCreditsStatsStatsGlobalKeyTypeCreditsGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetInferenceCreditsStatsStatsGlobalKeyTypeCreditsGetError =
	GetInferenceCreditsStatsStatsGlobalKeyTypeCreditsGetErrors[keyof GetInferenceCreditsStatsStatsGlobalKeyTypeCreditsGetErrors];

export type GetInferenceCreditsStatsStatsGlobalKeyTypeCreditsGetResponses = {
	/**
	 * Successful Response
	 */
	200: GlobalCreditsStats;
};

export type GetInferenceCreditsStatsStatsGlobalKeyTypeCreditsGetResponse =
	GetInferenceCreditsStatsStatsGlobalKeyTypeCreditsGetResponses[keyof GetInferenceCreditsStatsStatsGlobalKeyTypeCreditsGetResponses];

export type GetInferenceUsersStatsStatsGlobalKeyTypeUsersGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path: {
		key_type: InferenceKeyType;
	};
	query: {
		/**
		 * Start Date
		 *
		 * Start date in format YYYY-MM-DD
		 */
		start_date: string;
		/**
		 * End Date
		 *
		 * End date in format YYYY-MM-DD
		 */
		end_date: string;
		/**
		 * Rolling window: day (DAU), week (WAU), month (MAU)
		 */
		window?: UsersWindow;
	};
	url: "/stats/global/{key_type}/users";
};

export type GetInferenceUsersStatsStatsGlobalKeyTypeUsersGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetInferenceUsersStatsStatsGlobalKeyTypeUsersGetError =
	GetInferenceUsersStatsStatsGlobalKeyTypeUsersGetErrors[keyof GetInferenceUsersStatsStatsGlobalKeyTypeUsersGetErrors];

export type GetInferenceUsersStatsStatsGlobalKeyTypeUsersGetResponses = {
	/**
	 * Successful Response
	 */
	200: GlobalUsersStats;
};

export type GetInferenceUsersStatsStatsGlobalKeyTypeUsersGetResponse =
	GetInferenceUsersStatsStatsGlobalKeyTypeUsersGetResponses[keyof GetInferenceUsersStatsStatsGlobalKeyTypeUsersGetResponses];

export type GetAggregateUsersStatsStatsGlobalUsersGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query: {
		/**
		 * Start Date
		 *
		 * Start date in format YYYY-MM-DD
		 */
		start_date: string;
		/**
		 * End Date
		 *
		 * End date in format YYYY-MM-DD
		 */
		end_date: string;
		/**
		 * Rolling window: day (DAU), week (WAU), month (MAU)
		 */
		window?: UsersWindow;
	};
	url: "/stats/global/users";
};

export type GetAggregateUsersStatsStatsGlobalUsersGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetAggregateUsersStatsStatsGlobalUsersGetError =
	GetAggregateUsersStatsStatsGlobalUsersGetErrors[keyof GetAggregateUsersStatsStatsGlobalUsersGetErrors];

export type GetAggregateUsersStatsStatsGlobalUsersGetResponses = {
	/**
	 * Successful Response
	 */
	200: GlobalUsersStats;
};

export type GetAggregateUsersStatsStatsGlobalUsersGetResponse =
	GetAggregateUsersStatsStatsGlobalUsersGetResponses[keyof GetAggregateUsersStatsStatsGlobalUsersGetResponses];

export type GetGlobalSummaryStatsGlobalSummaryGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query: {
		/**
		 * Start Date
		 *
		 * Start date in format YYYY-MM-DD
		 */
		start_date: string;
		/**
		 * End Date
		 *
		 * End date in format YYYY-MM-DD
		 */
		end_date: string;
	};
	url: "/stats/global/summary";
};

export type GetGlobalSummaryStatsGlobalSummaryGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetGlobalSummaryStatsGlobalSummaryGetError =
	GetGlobalSummaryStatsGlobalSummaryGetErrors[keyof GetGlobalSummaryStatsGlobalSummaryGetErrors];

export type GetGlobalSummaryStatsGlobalSummaryGetResponses = {
	/**
	 * Successful Response
	 */
	200: GlobalSummaryStats;
};

export type GetGlobalSummaryStatsGlobalSummaryGetResponse =
	GetGlobalSummaryStatsGlobalSummaryGetResponses[keyof GetGlobalSummaryStatsGlobalSummaryGetResponses];

export type GetMessagesBySegmentStatsGlobalMessagesBySegmentGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query: {
		/**
		 * Start Date
		 *
		 * Start date in format YYYY-MM-DD
		 */
		start_date: string;
		/**
		 * End Date
		 *
		 * End date in format YYYY-MM-DD
		 */
		end_date: string;
	};
	url: "/stats/global/messages-by-segment";
};

export type GetMessagesBySegmentStatsGlobalMessagesBySegmentGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetMessagesBySegmentStatsGlobalMessagesBySegmentGetError =
	GetMessagesBySegmentStatsGlobalMessagesBySegmentGetErrors[keyof GetMessagesBySegmentStatsGlobalMessagesBySegmentGetErrors];

export type GetMessagesBySegmentStatsGlobalMessagesBySegmentGetResponses = {
	/**
	 * Successful Response
	 */
	200: GlobalSegmentMessagesStats;
};

export type GetMessagesBySegmentStatsGlobalMessagesBySegmentGetResponse =
	GetMessagesBySegmentStatsGlobalMessagesBySegmentGetResponses[keyof GetMessagesBySegmentStatsGlobalMessagesBySegmentGetResponses];

export type GetCallsBySegmentStatsGlobalKeyTypeCallsBySegmentGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path: {
		key_type: InferenceKeyType;
	};
	query: {
		/**
		 * Start Date
		 *
		 * Start date in format YYYY-MM-DD
		 */
		start_date: string;
		/**
		 * End Date
		 *
		 * End date in format YYYY-MM-DD
		 */
		end_date: string;
	};
	url: "/stats/global/{key_type}/calls-by-segment";
};

export type GetCallsBySegmentStatsGlobalKeyTypeCallsBySegmentGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetCallsBySegmentStatsGlobalKeyTypeCallsBySegmentGetError =
	GetCallsBySegmentStatsGlobalKeyTypeCallsBySegmentGetErrors[keyof GetCallsBySegmentStatsGlobalKeyTypeCallsBySegmentGetErrors];

export type GetCallsBySegmentStatsGlobalKeyTypeCallsBySegmentGetResponses = {
	/**
	 * Successful Response
	 */
	200: GlobalSegmentCallsStats;
};

export type GetCallsBySegmentStatsGlobalKeyTypeCallsBySegmentGetResponse =
	GetCallsBySegmentStatsGlobalKeyTypeCallsBySegmentGetResponses[keyof GetCallsBySegmentStatsGlobalKeyTypeCallsBySegmentGetResponses];

export type GetCreditsConsumptionStatsGlobalCreditsConsumptionGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query: {
		/**
		 * Start Date
		 *
		 * Start date in format YYYY-MM-DD
		 */
		start_date: string;
		/**
		 * End Date
		 *
		 * End date in format YYYY-MM-DD
		 */
		end_date: string;
	};
	url: "/stats/global/credits-consumption";
};

export type GetCreditsConsumptionStatsGlobalCreditsConsumptionGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetCreditsConsumptionStatsGlobalCreditsConsumptionGetError =
	GetCreditsConsumptionStatsGlobalCreditsConsumptionGetErrors[keyof GetCreditsConsumptionStatsGlobalCreditsConsumptionGetErrors];

export type GetCreditsConsumptionStatsGlobalCreditsConsumptionGetResponses = {
	/**
	 * Successful Response
	 */
	200: GlobalCreditsConsumptionStats;
};

export type GetCreditsConsumptionStatsGlobalCreditsConsumptionGetResponse =
	GetCreditsConsumptionStatsGlobalCreditsConsumptionGetResponses[keyof GetCreditsConsumptionStatsGlobalCreditsConsumptionGetResponses];

export type GetSubscriptionsStatsStatsGlobalSubscriptionsGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query?: never;
	url: "/stats/global/subscriptions";
};

export type GetSubscriptionsStatsStatsGlobalSubscriptionsGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetSubscriptionsStatsStatsGlobalSubscriptionsGetError =
	GetSubscriptionsStatsStatsGlobalSubscriptionsGetErrors[keyof GetSubscriptionsStatsStatsGlobalSubscriptionsGetErrors];

export type GetSubscriptionsStatsStatsGlobalSubscriptionsGetResponses = {
	/**
	 * Successful Response
	 */
	200: GlobalSubscriptionsStats;
};

export type GetSubscriptionsStatsStatsGlobalSubscriptionsGetResponse =
	GetSubscriptionsStatsStatsGlobalSubscriptionsGetResponses[keyof GetSubscriptionsStatsStatsGlobalSubscriptionsGetResponses];

export type GetSubscribersOverTimeStatsGlobalSubscribersOverTimeGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query: {
		/**
		 * Start Date
		 *
		 * Start date in format YYYY-MM-DD
		 */
		start_date: string;
		/**
		 * End Date
		 *
		 * End date in format YYYY-MM-DD
		 */
		end_date: string;
	};
	url: "/stats/global/subscribers-over-time";
};

export type GetSubscribersOverTimeStatsGlobalSubscribersOverTimeGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetSubscribersOverTimeStatsGlobalSubscribersOverTimeGetError =
	GetSubscribersOverTimeStatsGlobalSubscribersOverTimeGetErrors[keyof GetSubscribersOverTimeStatsGlobalSubscribersOverTimeGetErrors];

export type GetSubscribersOverTimeStatsGlobalSubscribersOverTimeGetResponses = {
	/**
	 * Successful Response
	 */
	200: GlobalSubscribersOverTimeStats;
};

export type GetSubscribersOverTimeStatsGlobalSubscribersOverTimeGetResponse =
	GetSubscribersOverTimeStatsGlobalSubscribersOverTimeGetResponses[keyof GetSubscribersOverTimeStatsGlobalSubscribersOverTimeGetResponses];

export type ProxyChatRequestChatCompletionsPostData = {
	body: ChatRequest;
	path?: never;
	query?: never;
	url: "/chat/completions";
};

export type ProxyChatRequestChatCompletionsPostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type ProxyChatRequestChatCompletionsPostError =
	ProxyChatRequestChatCompletionsPostErrors[keyof ProxyChatRequestChatCompletionsPostErrors];

export type ProxyChatRequestChatCompletionsPostResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type GetAnonUsageChatAnonUsageGetData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/chat/anon-usage";
};

export type GetAnonUsageChatAnonUsageGetResponses = {
	/**
	 * Successful Response
	 */
	200: AnonUsageResponse;
};

export type GetAnonUsageChatAnonUsageGetResponse =
	GetAnonUsageChatAnonUsageGetResponses[keyof GetAnonUsageChatAnonUsageGetResponses];

export type GetOrCreateApiKeyLiberclawApiKeyPostData = {
	body: LiberclawApiKeyRequest;
	headers: {
		/**
		 * X-Liberclaw-Token
		 */
		"x-liberclaw-token": string;
	};
	path?: never;
	query?: never;
	url: "/liberclaw/api-key";
};

export type GetOrCreateApiKeyLiberclawApiKeyPostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetOrCreateApiKeyLiberclawApiKeyPostError =
	GetOrCreateApiKeyLiberclawApiKeyPostErrors[keyof GetOrCreateApiKeyLiberclawApiKeyPostErrors];

export type GetOrCreateApiKeyLiberclawApiKeyPostResponses = {
	/**
	 * Successful Response
	 */
	200: LiberclawApiKeyResponse;
};

export type GetOrCreateApiKeyLiberclawApiKeyPostResponse =
	GetOrCreateApiKeyLiberclawApiKeyPostResponses[keyof GetOrCreateApiKeyLiberclawApiKeyPostResponses];

export type UpdateTierLiberclawTierPutData = {
	body: LiberclawTierUpdate;
	headers: {
		/**
		 * X-Liberclaw-Token
		 */
		"x-liberclaw-token": string;
	};
	path?: never;
	query?: never;
	url: "/liberclaw/tier";
};

export type UpdateTierLiberclawTierPutErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type UpdateTierLiberclawTierPutError = UpdateTierLiberclawTierPutErrors[keyof UpdateTierLiberclawTierPutErrors];

export type UpdateTierLiberclawTierPutResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type GetUserLiberclawUserGetData = {
	body?: never;
	headers: {
		/**
		 * X-Liberclaw-Token
		 */
		"x-liberclaw-token": string;
	};
	path?: never;
	query: {
		/**
		 * User Id
		 */
		user_id: string;
		/**
		 * User Type
		 */
		user_type: string;
	};
	url: "/liberclaw/user";
};

export type GetUserLiberclawUserGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetUserLiberclawUserGetError = GetUserLiberclawUserGetErrors[keyof GetUserLiberclawUserGetErrors];

export type GetUserLiberclawUserGetResponses = {
	/**
	 * Successful Response
	 */
	200: LiberclawUserResponse;
};

export type GetUserLiberclawUserGetResponse = GetUserLiberclawUserGetResponses[keyof GetUserLiberclawUserGetResponses];

export type GetX402PricesX402PricesGetData = {
	body?: never;
	headers: {
		/**
		 * X-Admin-Token
		 */
		"x-admin-token": string;
	};
	path?: never;
	query?: never;
	url: "/x402/prices";
};

export type GetX402PricesX402PricesGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetX402PricesX402PricesGetError = GetX402PricesX402PricesGetErrors[keyof GetX402PricesX402PricesGetErrors];

export type GetX402PricesX402PricesGetResponses = {
	/**
	 * Response Get X402 Prices X402 Prices Get
	 *
	 * Successful Response
	 */
	200: {
		[key: string]: {
			[key: string]: unknown;
		};
	};
};

export type GetX402PricesX402PricesGetResponse =
	GetX402PricesX402PricesGetResponses[keyof GetX402PricesX402PricesGetResponses];

export type ListProvidersPaymentsProvidersGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query?: never;
	url: "/payments/providers";
};

export type ListProvidersPaymentsProvidersGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type ListProvidersPaymentsProvidersGetError =
	ListProvidersPaymentsProvidersGetErrors[keyof ListProvidersPaymentsProvidersGetErrors];

export type ListProvidersPaymentsProvidersGetResponses = {
	/**
	 * Response List Providers Payments Providers Get
	 *
	 * Successful Response
	 */
	200: Array<PaymentProviderResponse>;
};

export type ListProvidersPaymentsProvidersGetResponse =
	ListProvidersPaymentsProvidersGetResponses[keyof ListProvidersPaymentsProvidersGetResponses];

export type ListTiersPaymentsTiersGetData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/payments/tiers";
};

export type ListTiersPaymentsTiersGetResponses = {
	/**
	 * Response List Tiers Payments Tiers Get
	 *
	 * Successful Response
	 */
	200: Array<TierResponse>;
};

export type ListTiersPaymentsTiersGetResponse =
	ListTiersPaymentsTiersGetResponses[keyof ListTiersPaymentsTiersGetResponses];

export type RegionPaymentsRegionGetData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/payments/region";
};

export type RegionPaymentsRegionGetResponses = {
	/**
	 * Successful Response
	 */
	200: RegionResponse;
};

export type RegionPaymentsRegionGetResponse = RegionPaymentsRegionGetResponses[keyof RegionPaymentsRegionGetResponses];

export type TopupPacksPaymentsTopupPacksGetData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/payments/topup-packs";
};

export type TopupPacksPaymentsTopupPacksGetResponses = {
	/**
	 * Response Topup Packs Payments Topup Packs Get
	 *
	 * Successful Response
	 */
	200: Array<TopupPackResponse>;
};

export type TopupPacksPaymentsTopupPacksGetResponse =
	TopupPacksPaymentsTopupPacksGetResponses[keyof TopupPacksPaymentsTopupPacksGetResponses];

export type TopupPaymentsTopupPostData = {
	body: TopupRequest;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query?: never;
	url: "/payments/topup";
};

export type TopupPaymentsTopupPostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type TopupPaymentsTopupPostError = TopupPaymentsTopupPostErrors[keyof TopupPaymentsTopupPostErrors];

export type TopupPaymentsTopupPostResponses = {
	/**
	 * Successful Response
	 */
	200: CheckoutResponse;
};

export type TopupPaymentsTopupPostResponse = TopupPaymentsTopupPostResponses[keyof TopupPaymentsTopupPostResponses];

export type SubscribePaymentsSubscribePostData = {
	body: SubscribeRequest;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query?: never;
	url: "/payments/subscribe";
};

export type SubscribePaymentsSubscribePostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type SubscribePaymentsSubscribePostError =
	SubscribePaymentsSubscribePostErrors[keyof SubscribePaymentsSubscribePostErrors];

export type SubscribePaymentsSubscribePostResponses = {
	/**
	 * Successful Response
	 */
	200: CheckoutResponse;
};

export type SubscribePaymentsSubscribePostResponse =
	SubscribePaymentsSubscribePostResponses[keyof SubscribePaymentsSubscribePostResponses];

export type UpgradePaymentsUpgradePostData = {
	body: SubscribeRequest;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query?: never;
	url: "/payments/upgrade";
};

export type UpgradePaymentsUpgradePostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type UpgradePaymentsUpgradePostError = UpgradePaymentsUpgradePostErrors[keyof UpgradePaymentsUpgradePostErrors];

export type UpgradePaymentsUpgradePostResponses = {
	/**
	 * Successful Response
	 */
	200: CheckoutResponse;
};

export type UpgradePaymentsUpgradePostResponse =
	UpgradePaymentsUpgradePostResponses[keyof UpgradePaymentsUpgradePostResponses];

export type DowngradePaymentsDowngradePostData = {
	body: DowngradeRequest;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query?: never;
	url: "/payments/downgrade";
};

export type DowngradePaymentsDowngradePostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type DowngradePaymentsDowngradePostError =
	DowngradePaymentsDowngradePostErrors[keyof DowngradePaymentsDowngradePostErrors];

export type DowngradePaymentsDowngradePostResponses = {
	/**
	 * Successful Response
	 */
	200: DowngradeResponse;
};

export type DowngradePaymentsDowngradePostResponse =
	DowngradePaymentsDowngradePostResponses[keyof DowngradePaymentsDowngradePostResponses];

export type CancelPaymentsCancelPostData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query?: never;
	url: "/payments/cancel";
};

export type CancelPaymentsCancelPostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type CancelPaymentsCancelPostError = CancelPaymentsCancelPostErrors[keyof CancelPaymentsCancelPostErrors];

export type CancelPaymentsCancelPostResponses = {
	/**
	 * Successful Response
	 */
	200: CancelResponse;
};

export type CancelPaymentsCancelPostResponse =
	CancelPaymentsCancelPostResponses[keyof CancelPaymentsCancelPostResponses];

export type ResumePaymentsResumePostData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query?: never;
	url: "/payments/resume";
};

export type ResumePaymentsResumePostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type ResumePaymentsResumePostError = ResumePaymentsResumePostErrors[keyof ResumePaymentsResumePostErrors];

export type ResumePaymentsResumePostResponses = {
	/**
	 * Successful Response
	 */
	200: ResumeResponse;
};

export type ResumePaymentsResumePostResponse =
	ResumePaymentsResumePostResponses[keyof ResumePaymentsResumePostResponses];

export type GetSubscriptionPaymentsSubscriptionGetData = {
	body?: never;
	headers?: {
		/**
		 * Authorization
		 */
		authorization?: string | null;
	};
	path?: never;
	query?: never;
	url: "/payments/subscription";
};

export type GetSubscriptionPaymentsSubscriptionGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetSubscriptionPaymentsSubscriptionGetError =
	GetSubscriptionPaymentsSubscriptionGetErrors[keyof GetSubscriptionPaymentsSubscriptionGetErrors];

export type GetSubscriptionPaymentsSubscriptionGetResponses = {
	/**
	 * Successful Response
	 */
	200: SubscriptionResponse;
};

export type GetSubscriptionPaymentsSubscriptionGetResponse =
	GetSubscriptionPaymentsSubscriptionGetResponses[keyof GetSubscriptionPaymentsSubscriptionGetResponses];

export type WebhookPaymentsWebhookProviderIdPostData = {
	body?: never;
	path: {
		/**
		 * Provider Id
		 */
		provider_id: string;
	};
	query?: never;
	url: "/payments/webhook/{provider_id}";
};

export type WebhookPaymentsWebhookProviderIdPostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type WebhookPaymentsWebhookProviderIdPostError =
	WebhookPaymentsWebhookProviderIdPostErrors[keyof WebhookPaymentsWebhookProviderIdPostErrors];

export type WebhookPaymentsWebhookProviderIdPostResponses = {
	/**
	 * Response Webhook Payments Webhook  Provider Id  Post
	 *
	 * Successful Response
	 */
	200: {
		[key: string]: unknown;
	};
};

export type WebhookPaymentsWebhookProviderIdPostResponse =
	WebhookPaymentsWebhookProviderIdPostResponses[keyof WebhookPaymentsWebhookProviderIdPostResponses];
